////////////////////////////////////////////////////////////////////////////
//
//  Venus Engine Header File.
//  Copyright (C), Venus Interactive Entertainment.2012
// -------------------------------------------------------------------------
//  File name:   wgl.h
//  Version:     v1.00
//  Created:     by GlSpecLoader
//  Compilers:   Visual Studio.NET
//  Description: 
// -------------------------------------------------------------------------
//  History:
//  http://www.venusie.com
////////////////////////////////////////////////////////////////////////////

#pragma once

#ifdef VE_WGL

extern "C"
{

#ifndef WGL_ACCESS_READ_ONLY_NV
#define WGL_ACCESS_READ_ONLY_NV 0x00000000
#endif

#ifndef WGL_ACCESS_READ_WRITE_NV
#define WGL_ACCESS_READ_WRITE_NV 0x00000001
#endif

#ifndef WGL_ACCESS_WRITE_DISCARD_NV
#define WGL_ACCESS_WRITE_DISCARD_NV 0x00000002
#endif

#ifndef WGL_FRONT_COLOR_BUFFER_BIT_ARB
#define WGL_FRONT_COLOR_BUFFER_BIT_ARB 0x00000001
#endif

#ifndef WGL_BACK_COLOR_BUFFER_BIT_ARB
#define WGL_BACK_COLOR_BUFFER_BIT_ARB 0x00000002
#endif

#ifndef WGL_DEPTH_BUFFER_BIT_ARB
#define WGL_DEPTH_BUFFER_BIT_ARB 0x00000004
#endif

#ifndef WGL_STENCIL_BUFFER_BIT_ARB
#define WGL_STENCIL_BUFFER_BIT_ARB 0x00000008
#endif

#ifndef WGL_CONTEXT_DEBUG_BIT_ARB
#define WGL_CONTEXT_DEBUG_BIT_ARB 0x00000001
#endif

#ifndef WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB
#define WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB 0x00000002
#endif

#ifndef WGL_CONTEXT_ROBUST_ACCESS_BIT_ARB
#define WGL_CONTEXT_ROBUST_ACCESS_BIT_ARB 0x00000004
#endif

#ifndef WGL_CONTEXT_RESET_ISOLATION_BIT_ARB
#define WGL_CONTEXT_RESET_ISOLATION_BIT_ARB 0x00000008
#endif

#ifndef WGL_CONTEXT_CORE_PROFILE_BIT_ARB
#define WGL_CONTEXT_CORE_PROFILE_BIT_ARB 0x00000001
#endif

#ifndef WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB
#define WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB 0x00000002
#endif

#ifndef WGL_CONTEXT_ES2_PROFILE_BIT_EXT
#define WGL_CONTEXT_ES2_PROFILE_BIT_EXT 0x00000004
#endif

#ifndef WGL_NUMBER_PIXEL_FORMATS_EXT
#define WGL_NUMBER_PIXEL_FORMATS_EXT 0x2000
#endif

#ifndef WGL_DRAW_TO_WINDOW_EXT
#define WGL_DRAW_TO_WINDOW_EXT 0x2001
#endif

#ifndef WGL_DRAW_TO_BITMAP_EXT
#define WGL_DRAW_TO_BITMAP_EXT 0x2002
#endif

#ifndef WGL_ACCELERATION_EXT
#define WGL_ACCELERATION_EXT 0x2003
#endif

#ifndef WGL_NEED_PALETTE_EXT
#define WGL_NEED_PALETTE_EXT 0x2004
#endif

#ifndef WGL_NEED_SYSTEM_PALETTE_EXT
#define WGL_NEED_SYSTEM_PALETTE_EXT 0x2005
#endif

#ifndef WGL_SWAP_LAYER_BUFFERS_EXT
#define WGL_SWAP_LAYER_BUFFERS_EXT 0x2006
#endif

#ifndef WGL_SWAP_METHOD_EXT
#define WGL_SWAP_METHOD_EXT 0x2007
#endif

#ifndef WGL_NUMBER_OVERLAYS_EXT
#define WGL_NUMBER_OVERLAYS_EXT 0x2008
#endif

#ifndef WGL_NUMBER_UNDERLAYS_EXT
#define WGL_NUMBER_UNDERLAYS_EXT 0x2009
#endif

#ifndef WGL_TRANSPARENT_EXT
#define WGL_TRANSPARENT_EXT 0x200A
#endif

#ifndef WGL_TRANSPARENT_VALUE_EXT
#define WGL_TRANSPARENT_VALUE_EXT 0x200B
#endif

#ifndef WGL_SHARE_DEPTH_EXT
#define WGL_SHARE_DEPTH_EXT 0x200C
#endif

#ifndef WGL_SHARE_STENCIL_EXT
#define WGL_SHARE_STENCIL_EXT 0x200D
#endif

#ifndef WGL_SHARE_ACCUM_EXT
#define WGL_SHARE_ACCUM_EXT 0x200E
#endif

#ifndef WGL_SUPPORT_GDI_EXT
#define WGL_SUPPORT_GDI_EXT 0x200F
#endif

#ifndef WGL_SUPPORT_OPENGL_EXT
#define WGL_SUPPORT_OPENGL_EXT 0x2010
#endif

#ifndef WGL_DOUBLE_BUFFER_EXT
#define WGL_DOUBLE_BUFFER_EXT 0x2011
#endif

#ifndef WGL_STEREO_EXT
#define WGL_STEREO_EXT 0x2012
#endif

#ifndef WGL_PIXEL_TYPE_EXT
#define WGL_PIXEL_TYPE_EXT 0x2013
#endif

#ifndef WGL_COLOR_BITS_EXT
#define WGL_COLOR_BITS_EXT 0x2014
#endif

#ifndef WGL_RED_BITS_EXT
#define WGL_RED_BITS_EXT 0x2015
#endif

#ifndef WGL_RED_SHIFT_EXT
#define WGL_RED_SHIFT_EXT 0x2016
#endif

#ifndef WGL_GREEN_BITS_EXT
#define WGL_GREEN_BITS_EXT 0x2017
#endif

#ifndef WGL_GREEN_SHIFT_EXT
#define WGL_GREEN_SHIFT_EXT 0x2018
#endif

#ifndef WGL_BLUE_BITS_EXT
#define WGL_BLUE_BITS_EXT 0x2019
#endif

#ifndef WGL_BLUE_SHIFT_EXT
#define WGL_BLUE_SHIFT_EXT 0x201A
#endif

#ifndef WGL_ALPHA_BITS_EXT
#define WGL_ALPHA_BITS_EXT 0x201B
#endif

#ifndef WGL_ALPHA_SHIFT_EXT
#define WGL_ALPHA_SHIFT_EXT 0x201C
#endif

#ifndef WGL_ACCUM_BITS_EXT
#define WGL_ACCUM_BITS_EXT 0x201D
#endif

#ifndef WGL_ACCUM_RED_BITS_EXT
#define WGL_ACCUM_RED_BITS_EXT 0x201E
#endif

#ifndef WGL_ACCUM_GREEN_BITS_EXT
#define WGL_ACCUM_GREEN_BITS_EXT 0x201F
#endif

#ifndef WGL_ACCUM_BLUE_BITS_EXT
#define WGL_ACCUM_BLUE_BITS_EXT 0x2020
#endif

#ifndef WGL_ACCUM_ALPHA_BITS_EXT
#define WGL_ACCUM_ALPHA_BITS_EXT 0x2021
#endif

#ifndef WGL_DEPTH_BITS_EXT
#define WGL_DEPTH_BITS_EXT 0x2022
#endif

#ifndef WGL_STENCIL_BITS_EXT
#define WGL_STENCIL_BITS_EXT 0x2023
#endif

#ifndef WGL_AUX_BUFFERS_EXT
#define WGL_AUX_BUFFERS_EXT 0x2024
#endif

#ifndef WGL_NO_ACCELERATION_EXT
#define WGL_NO_ACCELERATION_EXT 0x2025
#endif

#ifndef WGL_GENERIC_ACCELERATION_EXT
#define WGL_GENERIC_ACCELERATION_EXT 0x2026
#endif

#ifndef WGL_FULL_ACCELERATION_EXT
#define WGL_FULL_ACCELERATION_EXT 0x2027
#endif

#ifndef WGL_SWAP_EXCHANGE_EXT
#define WGL_SWAP_EXCHANGE_EXT 0x2028
#endif

#ifndef WGL_SWAP_COPY_EXT
#define WGL_SWAP_COPY_EXT 0x2029
#endif

#ifndef WGL_SWAP_UNDEFINED_EXT
#define WGL_SWAP_UNDEFINED_EXT 0x202A
#endif

#ifndef WGL_TYPE_RGBA_EXT
#define WGL_TYPE_RGBA_EXT 0x202B
#endif

#ifndef WGL_TYPE_COLORINDEX_EXT
#define WGL_TYPE_COLORINDEX_EXT 0x202C
#endif

#ifndef WGL_NUMBER_PIXEL_FORMATS_ARB
#define WGL_NUMBER_PIXEL_FORMATS_ARB 0x2000
#endif

#ifndef WGL_DRAW_TO_WINDOW_ARB
#define WGL_DRAW_TO_WINDOW_ARB 0x2001
#endif

#ifndef WGL_DRAW_TO_BITMAP_ARB
#define WGL_DRAW_TO_BITMAP_ARB 0x2002
#endif

#ifndef WGL_ACCELERATION_ARB
#define WGL_ACCELERATION_ARB 0x2003
#endif

#ifndef WGL_NEED_PALETTE_ARB
#define WGL_NEED_PALETTE_ARB 0x2004
#endif

#ifndef WGL_NEED_SYSTEM_PALETTE_ARB
#define WGL_NEED_SYSTEM_PALETTE_ARB 0x2005
#endif

#ifndef WGL_SWAP_LAYER_BUFFERS_ARB
#define WGL_SWAP_LAYER_BUFFERS_ARB 0x2006
#endif

#ifndef WGL_SWAP_METHOD_ARB
#define WGL_SWAP_METHOD_ARB 0x2007
#endif

#ifndef WGL_NUMBER_OVERLAYS_ARB
#define WGL_NUMBER_OVERLAYS_ARB 0x2008
#endif

#ifndef WGL_NUMBER_UNDERLAYS_ARB
#define WGL_NUMBER_UNDERLAYS_ARB 0x2009
#endif

#ifndef WGL_TRANSPARENT_ARB
#define WGL_TRANSPARENT_ARB 0x200A
#endif

#ifndef WGL_SHARE_DEPTH_ARB
#define WGL_SHARE_DEPTH_ARB 0x200C
#endif

#ifndef WGL_SHARE_STENCIL_ARB
#define WGL_SHARE_STENCIL_ARB 0x200D
#endif

#ifndef WGL_SHARE_ACCUM_ARB
#define WGL_SHARE_ACCUM_ARB 0x200E
#endif

#ifndef WGL_SUPPORT_GDI_ARB
#define WGL_SUPPORT_GDI_ARB 0x200F
#endif

#ifndef WGL_SUPPORT_OPENGL_ARB
#define WGL_SUPPORT_OPENGL_ARB 0x2010
#endif

#ifndef WGL_DOUBLE_BUFFER_ARB
#define WGL_DOUBLE_BUFFER_ARB 0x2011
#endif

#ifndef WGL_STEREO_ARB
#define WGL_STEREO_ARB 0x2012
#endif

#ifndef WGL_PIXEL_TYPE_ARB
#define WGL_PIXEL_TYPE_ARB 0x2013
#endif

#ifndef WGL_COLOR_BITS_ARB
#define WGL_COLOR_BITS_ARB 0x2014
#endif

#ifndef WGL_RED_BITS_ARB
#define WGL_RED_BITS_ARB 0x2015
#endif

#ifndef WGL_RED_SHIFT_ARB
#define WGL_RED_SHIFT_ARB 0x2016
#endif

#ifndef WGL_GREEN_BITS_ARB
#define WGL_GREEN_BITS_ARB 0x2017
#endif

#ifndef WGL_GREEN_SHIFT_ARB
#define WGL_GREEN_SHIFT_ARB 0x2018
#endif

#ifndef WGL_BLUE_BITS_ARB
#define WGL_BLUE_BITS_ARB 0x2019
#endif

#ifndef WGL_BLUE_SHIFT_ARB
#define WGL_BLUE_SHIFT_ARB 0x201A
#endif

#ifndef WGL_ALPHA_BITS_ARB
#define WGL_ALPHA_BITS_ARB 0x201B
#endif

#ifndef WGL_ALPHA_SHIFT_ARB
#define WGL_ALPHA_SHIFT_ARB 0x201C
#endif

#ifndef WGL_ACCUM_BITS_ARB
#define WGL_ACCUM_BITS_ARB 0x201D
#endif

#ifndef WGL_ACCUM_RED_BITS_ARB
#define WGL_ACCUM_RED_BITS_ARB 0x201E
#endif

#ifndef WGL_ACCUM_GREEN_BITS_ARB
#define WGL_ACCUM_GREEN_BITS_ARB 0x201F
#endif

#ifndef WGL_ACCUM_BLUE_BITS_ARB
#define WGL_ACCUM_BLUE_BITS_ARB 0x2020
#endif

#ifndef WGL_ACCUM_ALPHA_BITS_ARB
#define WGL_ACCUM_ALPHA_BITS_ARB 0x2021
#endif

#ifndef WGL_DEPTH_BITS_ARB
#define WGL_DEPTH_BITS_ARB 0x2022
#endif

#ifndef WGL_STENCIL_BITS_ARB
#define WGL_STENCIL_BITS_ARB 0x2023
#endif

#ifndef WGL_AUX_BUFFERS_ARB
#define WGL_AUX_BUFFERS_ARB 0x2024
#endif

#ifndef WGL_NO_ACCELERATION_ARB
#define WGL_NO_ACCELERATION_ARB 0x2025
#endif

#ifndef WGL_GENERIC_ACCELERATION_ARB
#define WGL_GENERIC_ACCELERATION_ARB 0x2026
#endif

#ifndef WGL_FULL_ACCELERATION_ARB
#define WGL_FULL_ACCELERATION_ARB 0x2027
#endif

#ifndef WGL_SWAP_EXCHANGE_ARB
#define WGL_SWAP_EXCHANGE_ARB 0x2028
#endif

#ifndef WGL_SWAP_COPY_ARB
#define WGL_SWAP_COPY_ARB 0x2029
#endif

#ifndef WGL_SWAP_UNDEFINED_ARB
#define WGL_SWAP_UNDEFINED_ARB 0x202A
#endif

#ifndef WGL_TYPE_RGBA_ARB
#define WGL_TYPE_RGBA_ARB 0x202B
#endif

#ifndef WGL_TYPE_COLORINDEX_ARB
#define WGL_TYPE_COLORINDEX_ARB 0x202C
#endif

#ifndef WGL_DRAW_TO_PBUFFER_ARB
#define WGL_DRAW_TO_PBUFFER_ARB 0x202D
#endif

#ifndef WGL_MAX_PBUFFER_PIXELS_ARB
#define WGL_MAX_PBUFFER_PIXELS_ARB 0x202E
#endif

#ifndef WGL_MAX_PBUFFER_WIDTH_ARB
#define WGL_MAX_PBUFFER_WIDTH_ARB 0x202F
#endif

#ifndef WGL_MAX_PBUFFER_HEIGHT_ARB
#define WGL_MAX_PBUFFER_HEIGHT_ARB 0x2030
#endif

#ifndef WGL_PBUFFER_LARGEST_ARB
#define WGL_PBUFFER_LARGEST_ARB 0x2033
#endif

#ifndef WGL_PBUFFER_WIDTH_ARB
#define WGL_PBUFFER_WIDTH_ARB 0x2034
#endif

#ifndef WGL_PBUFFER_HEIGHT_ARB
#define WGL_PBUFFER_HEIGHT_ARB 0x2035
#endif

#ifndef WGL_TRANSPARENT_RED_VALUE_ARB
#define WGL_TRANSPARENT_RED_VALUE_ARB 0x2037
#endif

#ifndef WGL_TRANSPARENT_GREEN_VALUE_ARB
#define WGL_TRANSPARENT_GREEN_VALUE_ARB 0x2038
#endif

#ifndef WGL_TRANSPARENT_BLUE_VALUE_ARB
#define WGL_TRANSPARENT_BLUE_VALUE_ARB 0x2039
#endif

#ifndef WGL_TRANSPARENT_ALPHA_VALUE_ARB
#define WGL_TRANSPARENT_ALPHA_VALUE_ARB 0x203A
#endif

#ifndef WGL_TRANSPARENT_INDEX_VALUE_ARB
#define WGL_TRANSPARENT_INDEX_VALUE_ARB 0x203B
#endif

#ifndef WGL_DRAW_TO_PBUFFER_EXT
#define WGL_DRAW_TO_PBUFFER_EXT 0x202D
#endif

#ifndef WGL_MAX_PBUFFER_PIXELS_EXT
#define WGL_MAX_PBUFFER_PIXELS_EXT 0x202E
#endif

#ifndef WGL_MAX_PBUFFER_WIDTH_EXT
#define WGL_MAX_PBUFFER_WIDTH_EXT 0x202F
#endif

#ifndef WGL_MAX_PBUFFER_HEIGHT_EXT
#define WGL_MAX_PBUFFER_HEIGHT_EXT 0x2030
#endif

#ifndef WGL_OPTIMAL_PBUFFER_WIDTH_EXT
#define WGL_OPTIMAL_PBUFFER_WIDTH_EXT 0x2031
#endif

#ifndef WGL_OPTIMAL_PBUFFER_HEIGHT_EXT
#define WGL_OPTIMAL_PBUFFER_HEIGHT_EXT 0x2032
#endif

#ifndef WGL_PBUFFER_LARGEST_EXT
#define WGL_PBUFFER_LARGEST_EXT 0x2033
#endif

#ifndef WGL_PBUFFER_WIDTH_EXT
#define WGL_PBUFFER_WIDTH_EXT 0x2034
#endif

#ifndef WGL_PBUFFER_HEIGHT_EXT
#define WGL_PBUFFER_HEIGHT_EXT 0x2035
#endif

#ifndef WGL_DRAW_TO_PBUFFER_ARB
#define WGL_DRAW_TO_PBUFFER_ARB 0x202D
#endif

#ifndef WGL_MAX_PBUFFER_PIXELS_ARB
#define WGL_MAX_PBUFFER_PIXELS_ARB 0x202E
#endif

#ifndef WGL_MAX_PBUFFER_WIDTH_ARB
#define WGL_MAX_PBUFFER_WIDTH_ARB 0x202F
#endif

#ifndef WGL_MAX_PBUFFER_HEIGHT_ARB
#define WGL_MAX_PBUFFER_HEIGHT_ARB 0x2030
#endif

#ifndef WGL_PBUFFER_LARGEST_ARB
#define WGL_PBUFFER_LARGEST_ARB 0x2033
#endif

#ifndef WGL_PBUFFER_WIDTH_ARB
#define WGL_PBUFFER_WIDTH_ARB 0x2034
#endif

#ifndef WGL_PBUFFER_HEIGHT_ARB
#define WGL_PBUFFER_HEIGHT_ARB 0x2035
#endif

#ifndef WGL_PBUFFER_LOST_ARB
#define WGL_PBUFFER_LOST_ARB 0x2036
#endif

#ifndef WGL_DEPTH_FLOAT_EXT
#define WGL_DEPTH_FLOAT_EXT 0x2040
#endif

#ifndef WGL_SAMPLE_BUFFERS_EXT
#define WGL_SAMPLE_BUFFERS_EXT 0x2041
#endif

#ifndef WGL_SAMPLES_EXT
#define WGL_SAMPLES_EXT 0x2042
#endif

#ifndef WGL_SAMPLE_BUFFERS_ARB
#define WGL_SAMPLE_BUFFERS_ARB 0x2041
#endif

#ifndef WGL_SAMPLES_ARB
#define WGL_SAMPLES_ARB 0x2042
#endif

#ifndef WGL_COVERAGE_SAMPLES_NV
#define WGL_COVERAGE_SAMPLES_NV 0x2042
#endif

#ifndef ERROR_INVALID_PIXEL_TYPE_EXT
#define ERROR_INVALID_PIXEL_TYPE_EXT 0x2043
#endif

#ifndef ERROR_INVALID_PIXEL_TYPE_ARB
#define ERROR_INVALID_PIXEL_TYPE_ARB 0x2043
#endif

#ifndef ERROR_INCOMPATIBLE_DEVICE_CONTEXTS_ARB
#define ERROR_INCOMPATIBLE_DEVICE_CONTEXTS_ARB 0x2054
#endif

#ifndef WGL_GENLOCK_SOURCE_MULTIVIEW_I3D
#define WGL_GENLOCK_SOURCE_MULTIVIEW_I3D 0x2044
#endif

#ifndef WGL_GENLOCK_SOURCE_EXTENAL_SYNC_I3D
#define WGL_GENLOCK_SOURCE_EXTENAL_SYNC_I3D 0x2045
#endif

#ifndef WGL_GENLOCK_SOURCE_EXTENAL_FIELD_I3D
#define WGL_GENLOCK_SOURCE_EXTENAL_FIELD_I3D 0x2046
#endif

#ifndef WGL_GENLOCK_SOURCE_EXTENAL_TTL_I3D
#define WGL_GENLOCK_SOURCE_EXTENAL_TTL_I3D 0x2047
#endif

#ifndef WGL_GENLOCK_SOURCE_DIGITAL_SYNC_I3D
#define WGL_GENLOCK_SOURCE_DIGITAL_SYNC_I3D 0x2048
#endif

#ifndef WGL_GENLOCK_SOURCE_DIGITAL_FIELD_I3D
#define WGL_GENLOCK_SOURCE_DIGITAL_FIELD_I3D 0x2049
#endif

#ifndef WGL_GENLOCK_SOURCE_EDGE_FALLING_I3D
#define WGL_GENLOCK_SOURCE_EDGE_FALLING_I3D 0x204A
#endif

#ifndef WGL_GENLOCK_SOURCE_EDGE_RISING_I3D
#define WGL_GENLOCK_SOURCE_EDGE_RISING_I3D 0x204B
#endif

#ifndef WGL_GENLOCK_SOURCE_EDGE_BOTH_I3D
#define WGL_GENLOCK_SOURCE_EDGE_BOTH_I3D 0x204C
#endif

#ifndef WGL_GAMMA_TABLE_SIZE_I3D
#define WGL_GAMMA_TABLE_SIZE_I3D 0x204E
#endif

#ifndef WGL_GAMMA_EXCLUDE_DESKTOP_I3D
#define WGL_GAMMA_EXCLUDE_DESKTOP_I3D 0x204F
#endif

#ifndef WGL_DIGITAL_VIDEO_CURSOR_ALPHA_FRAMEBUFFER_I3D
#define WGL_DIGITAL_VIDEO_CURSOR_ALPHA_FRAMEBUFFER_I3D 0x2050
#endif

#ifndef WGL_DIGITAL_VIDEO_CURSOR_ALPHA_VALUE_I3D
#define WGL_DIGITAL_VIDEO_CURSOR_ALPHA_VALUE_I3D 0x2051
#endif

#ifndef WGL_DIGITAL_VIDEO_CURSOR_INCLUDED_I3D
#define WGL_DIGITAL_VIDEO_CURSOR_INCLUDED_I3D 0x2052
#endif

#ifndef WGL_DIGITAL_VIDEO_GAMMA_CORRECTED_I3D
#define WGL_DIGITAL_VIDEO_GAMMA_CORRECTED_I3D 0x2053
#endif

#ifndef WGL_STEREO_EMITTER_ENABLE_3DL
#define WGL_STEREO_EMITTER_ENABLE_3DL 0x2055
#endif

#ifndef WGL_STEREO_EMITTER_DISABLE_3DL
#define WGL_STEREO_EMITTER_DISABLE_3DL 0x2056
#endif

#ifndef WGL_STEREO_POLARITY_NORMAL_3DL
#define WGL_STEREO_POLARITY_NORMAL_3DL 0x2057
#endif

#ifndef WGL_STEREO_POLARITY_INVERT_3DL
#define WGL_STEREO_POLARITY_INVERT_3DL 0x2058
#endif

#ifndef WGL_SAMPLE_BUFFERS_3DFX
#define WGL_SAMPLE_BUFFERS_3DFX 0x2060
#endif

#ifndef WGL_SAMPLES_3DFX
#define WGL_SAMPLES_3DFX 0x2061
#endif

#ifndef WGL_BIND_TO_TEXTURE_RGB_ARB
#define WGL_BIND_TO_TEXTURE_RGB_ARB 0x2070
#endif

#ifndef WGL_BIND_TO_TEXTURE_RGBA_ARB
#define WGL_BIND_TO_TEXTURE_RGBA_ARB 0x2071
#endif

#ifndef WGL_TEXTURE_FORMAT_ARB
#define WGL_TEXTURE_FORMAT_ARB 0x2072
#endif

#ifndef WGL_TEXTURE_TARGET_ARB
#define WGL_TEXTURE_TARGET_ARB 0x2073
#endif

#ifndef WGL_MIPMAP_TEXTURE_ARB
#define WGL_MIPMAP_TEXTURE_ARB 0x2074
#endif

#ifndef WGL_TEXTURE_RGB_ARB
#define WGL_TEXTURE_RGB_ARB 0x2075
#endif

#ifndef WGL_TEXTURE_RGBA_ARB
#define WGL_TEXTURE_RGBA_ARB 0x2076
#endif

#ifndef WGL_NO_TEXTURE_ARB
#define WGL_NO_TEXTURE_ARB 0x2077
#endif

#ifndef WGL_TEXTURE_CUBE_MAP_ARB
#define WGL_TEXTURE_CUBE_MAP_ARB 0x2078
#endif

#ifndef WGL_TEXTURE_1D_ARB
#define WGL_TEXTURE_1D_ARB 0x2079
#endif

#ifndef WGL_TEXTURE_2D_ARB
#define WGL_TEXTURE_2D_ARB 0x207A
#endif

#ifndef WGL_MIPMAP_LEVEL_ARB
#define WGL_MIPMAP_LEVEL_ARB 0x207B
#endif

#ifndef WGL_CUBE_MAP_FACE_ARB
#define WGL_CUBE_MAP_FACE_ARB 0x207C
#endif

#ifndef WGL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB
#define WGL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB 0x207D
#endif

#ifndef WGL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB
#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB 0x207E
#endif

#ifndef WGL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB
#define WGL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB 0x207F
#endif

#ifndef WGL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB
#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB 0x2080
#endif

#ifndef WGL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB
#define WGL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB 0x2081
#endif

#ifndef WGL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB
#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB 0x2082
#endif

#ifndef WGL_FRONT_LEFT_ARB
#define WGL_FRONT_LEFT_ARB 0x2083
#endif

#ifndef WGL_FRONT_RIGHT_ARB
#define WGL_FRONT_RIGHT_ARB 0x2084
#endif

#ifndef WGL_BACK_LEFT_ARB
#define WGL_BACK_LEFT_ARB 0x2085
#endif

#ifndef WGL_BACK_RIGHT_ARB
#define WGL_BACK_RIGHT_ARB 0x2086
#endif

#ifndef WGL_AUX0_ARB
#define WGL_AUX0_ARB 0x2087
#endif

#ifndef WGL_AUX1_ARB
#define WGL_AUX1_ARB 0x2088
#endif

#ifndef WGL_AUX2_ARB
#define WGL_AUX2_ARB 0x2089
#endif

#ifndef WGL_AUX3_ARB
#define WGL_AUX3_ARB 0x208A
#endif

#ifndef WGL_AUX4_ARB
#define WGL_AUX4_ARB 0x208B
#endif

#ifndef WGL_AUX5_ARB
#define WGL_AUX5_ARB 0x208C
#endif

#ifndef WGL_AUX6_ARB
#define WGL_AUX6_ARB 0x208D
#endif

#ifndef WGL_AUX7_ARB
#define WGL_AUX7_ARB 0x208E
#endif

#ifndef WGL_AUX8_ARB
#define WGL_AUX8_ARB 0x208F
#endif

#ifndef WGL_AUX9_ARB
#define WGL_AUX9_ARB 0x2090
#endif

#ifndef WGL_CONTEXT_MAJOR_VERSION_ARB
#define WGL_CONTEXT_MAJOR_VERSION_ARB 0x2091
#endif

#ifndef WGL_CONTEXT_MINOR_VERSION_ARB
#define WGL_CONTEXT_MINOR_VERSION_ARB 0x2092
#endif

#ifndef WGL_CONTEXT_LAYER_PLANE_ARB
#define WGL_CONTEXT_LAYER_PLANE_ARB 0x2093
#endif

#ifndef WGL_CONTEXT_FLAGS_ARB
#define WGL_CONTEXT_FLAGS_ARB 0x2094
#endif

#ifndef ERROR_INVALID_PROFILE_ARB
#define ERROR_INVALID_PROFILE_ARB 0x2096
#endif

#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_RGB_NV
#define WGL_BIND_TO_TEXTURE_RECTANGLE_RGB_NV 0x20A0
#endif

#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_RGBA_NV
#define WGL_BIND_TO_TEXTURE_RECTANGLE_RGBA_NV 0x20A1
#endif

#ifndef WGL_TEXTURE_RECTANGLE_NV
#define WGL_TEXTURE_RECTANGLE_NV 0x20A2
#endif

#ifndef WGL_BIND_TO_TEXTURE_DEPTH_NV
#define WGL_BIND_TO_TEXTURE_DEPTH_NV 0x20A3
#endif

#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_DEPTH_NV
#define WGL_BIND_TO_TEXTURE_RECTANGLE_DEPTH_NV 0x20A4
#endif

#ifndef WGL_DEPTH_TEXTURE_FORMAT_NV
#define WGL_DEPTH_TEXTURE_FORMAT_NV 0x20A5
#endif

#ifndef WGL_TEXTURE_DEPTH_COMPONENT_NV
#define WGL_TEXTURE_DEPTH_COMPONENT_NV 0x20A6
#endif

#ifndef WGL_DEPTH_COMPONENT_NV
#define WGL_DEPTH_COMPONENT_NV 0x20A7
#endif

#ifndef WGL_TYPE_RGBA_UNSIGNED_FLOAT_EXT
#define WGL_TYPE_RGBA_UNSIGNED_FLOAT_EXT 0x20A8
#endif

#ifndef WGL_FRAMEBUFFER_SRGB_CAPABLE_ARB
#define WGL_FRAMEBUFFER_SRGB_CAPABLE_ARB 0x20A9
#endif

#ifndef WGL_FRAMEBUFFER_SRGB_CAPABLE_EXT
#define WGL_FRAMEBUFFER_SRGB_CAPABLE_EXT 0x20A9
#endif

#ifndef WGL_FLOAT_COMPONENTS_NV
#define WGL_FLOAT_COMPONENTS_NV 0x20B0
#endif

#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_R_NV
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_R_NV 0x20B1
#endif

#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RG_NV
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RG_NV 0x20B2
#endif

#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGB_NV
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGB_NV 0x20B3
#endif

#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGBA_NV
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGBA_NV 0x20B4
#endif

#ifndef WGL_TEXTURE_FLOAT_R_NV
#define WGL_TEXTURE_FLOAT_R_NV 0x20B5
#endif

#ifndef WGL_TEXTURE_FLOAT_RG_NV
#define WGL_TEXTURE_FLOAT_RG_NV 0x20B6
#endif

#ifndef WGL_TEXTURE_FLOAT_RGB_NV
#define WGL_TEXTURE_FLOAT_RGB_NV 0x20B7
#endif

#ifndef WGL_TEXTURE_FLOAT_RGBA_NV
#define WGL_TEXTURE_FLOAT_RGBA_NV 0x20B8
#endif

#ifndef WGL_COLOR_SAMPLES_NV
#define WGL_COLOR_SAMPLES_NV 0x20B9
#endif

#ifndef WGL_BIND_TO_VIDEO_RGB_NV
#define WGL_BIND_TO_VIDEO_RGB_NV 0x20C0
#endif

#ifndef WGL_BIND_TO_VIDEO_RGBA_NV
#define WGL_BIND_TO_VIDEO_RGBA_NV 0x20C1
#endif

#ifndef WGL_BIND_TO_VIDEO_RGB_AND_DEPTH_NV
#define WGL_BIND_TO_VIDEO_RGB_AND_DEPTH_NV 0x20C2
#endif

#ifndef WGL_VIDEO_OUT_COLOR_NV
#define WGL_VIDEO_OUT_COLOR_NV 0x20C3
#endif

#ifndef WGL_VIDEO_OUT_ALPHA_NV
#define WGL_VIDEO_OUT_ALPHA_NV 0x20C4
#endif

#ifndef WGL_VIDEO_OUT_DEPTH_NV
#define WGL_VIDEO_OUT_DEPTH_NV 0x20C5
#endif

#ifndef WGL_VIDEO_OUT_COLOR_AND_ALPHA_NV
#define WGL_VIDEO_OUT_COLOR_AND_ALPHA_NV 0x20C6
#endif

#ifndef WGL_VIDEO_OUT_COLOR_AND_DEPTH_NV
#define WGL_VIDEO_OUT_COLOR_AND_DEPTH_NV 0x20C7
#endif

#ifndef WGL_VIDEO_OUT_FRAME
#define WGL_VIDEO_OUT_FRAME 0x20C8
#endif

#ifndef WGL_VIDEO_OUT_FIELD_1
#define WGL_VIDEO_OUT_FIELD_1 0x20C9
#endif

#ifndef WGL_VIDEO_OUT_FIELD_2
#define WGL_VIDEO_OUT_FIELD_2 0x20CA
#endif

#ifndef WGL_VIDEO_OUT_STACKED_FIELDS_1_2
#define WGL_VIDEO_OUT_STACKED_FIELDS_1_2 0x20CB
#endif

#ifndef WGL_VIDEO_OUT_STACKED_FIELDS_2_1
#define WGL_VIDEO_OUT_STACKED_FIELDS_2_1 0x20CC
#endif

#ifndef WGL_UNIQUE_ID_NV
#define WGL_UNIQUE_ID_NV 0x20CE
#endif

#ifndef WGL_NUM_VIDEO_CAPTURE_SLOTS_NV
#define WGL_NUM_VIDEO_CAPTURE_SLOTS_NV 0x20CF
#endif

#ifndef WGL_ERROR_INCOMPATIBLE_AFFINITY_MASKS_NV
#define WGL_ERROR_INCOMPATIBLE_AFFINITY_MASKS_NV 0x20D0
#endif

#ifndef WGL_ERROR_MISSING_AFFINITY_MASK_NV
#define WGL_ERROR_MISSING_AFFINITY_MASK_NV 0x20D1
#endif

#ifndef WGL_NUM_VIDEO_SLOTS_NV
#define WGL_NUM_VIDEO_SLOTS_NV 0x20F0
#endif

#ifndef WGL_TYPE_RGBA_FLOAT_ARB
#define WGL_TYPE_RGBA_FLOAT_ARB 0x21A0
#endif

#ifndef WGL_TYPE_RGBA_FLOAT_ATI
#define WGL_TYPE_RGBA_FLOAT_ATI 0x21A0
#endif

#ifndef WGL_GPU_VENDOR_AMD
#define WGL_GPU_VENDOR_AMD 0x1F00
#endif

#ifndef WGL_GPU_RENDERER_STRING_AMD
#define WGL_GPU_RENDERER_STRING_AMD 0x1F01
#endif

#ifndef WGL_GPU_OPENGL_VERSION_STRING_AMD
#define WGL_GPU_OPENGL_VERSION_STRING_AMD 0x1F02
#endif

#ifndef WGL_GPU_FASTEST_TARGET_GPUS_AMD
#define WGL_GPU_FASTEST_TARGET_GPUS_AMD 0x21A2
#endif

#ifndef WGL_GPU_RAM_AMD
#define WGL_GPU_RAM_AMD 0x21A3
#endif

#ifndef WGL_GPU_CLOCK_AMD
#define WGL_GPU_CLOCK_AMD 0x21A4
#endif

#ifndef WGL_GPU_NUM_PIPES_AMD
#define WGL_GPU_NUM_PIPES_AMD 0x21A5
#endif

#ifndef WGL_GPU_NUM_SIMD_AMD
#define WGL_GPU_NUM_SIMD_AMD 0x21A6
#endif

#ifndef WGL_GPU_NUM_RB_AMD
#define WGL_GPU_NUM_RB_AMD 0x21A7
#endif

#ifndef WGL_GPU_NUM_SPI_AMD
#define WGL_GPU_NUM_SPI_AMD 0x21A8
#endif

#ifndef WGL_LOSE_CONTEXT_ON_RESET_ARB
#define WGL_LOSE_CONTEXT_ON_RESET_ARB 0x8252
#endif

#ifndef WGL_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB
#define WGL_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB 0x8256
#endif

#ifndef WGL_NO_RESET_NOTIFICATION_ARB
#define WGL_NO_RESET_NOTIFICATION_ARB 0x8261
#endif

#ifndef WGL_CONTEXT_PROFILE_MASK_ARB
#define WGL_CONTEXT_PROFILE_MASK_ARB 0x9126
#endif


/* Header file version number */
/* wglext.h last updated 2012/01/04 */
/* Current version at http://www.opengl.org/registry/ */
#define WGL_WGLEXT_VERSION 24
#ifndef WGL_FRONT_COLOR_BUFFER_BIT_ARB
#define WGL_FRONT_COLOR_BUFFER_BIT_ARB 0x00000001
#endif

#ifndef WGL_BACK_COLOR_BUFFER_BIT_ARB
#define WGL_BACK_COLOR_BUFFER_BIT_ARB 0x00000002
#endif

#ifndef WGL_DEPTH_BUFFER_BIT_ARB
#define WGL_DEPTH_BUFFER_BIT_ARB 0x00000004
#endif

#ifndef WGL_STENCIL_BUFFER_BIT_ARB
#define WGL_STENCIL_BUFFER_BIT_ARB 0x00000008
#endif

#ifndef WGL_SAMPLE_BUFFERS_ARB
#define WGL_SAMPLE_BUFFERS_ARB 0x2041
#endif

#ifndef WGL_SAMPLES_ARB
#define WGL_SAMPLES_ARB 0x2042
#endif

#ifndef WGL_NUMBER_PIXEL_FORMATS_ARB
#define WGL_NUMBER_PIXEL_FORMATS_ARB 0x2000
#endif

#ifndef WGL_DRAW_TO_WINDOW_ARB
#define WGL_DRAW_TO_WINDOW_ARB 0x2001
#endif

#ifndef WGL_DRAW_TO_BITMAP_ARB
#define WGL_DRAW_TO_BITMAP_ARB 0x2002
#endif

#ifndef WGL_ACCELERATION_ARB
#define WGL_ACCELERATION_ARB 0x2003
#endif

#ifndef WGL_NEED_PALETTE_ARB
#define WGL_NEED_PALETTE_ARB 0x2004
#endif

#ifndef WGL_NEED_SYSTEM_PALETTE_ARB
#define WGL_NEED_SYSTEM_PALETTE_ARB 0x2005
#endif

#ifndef WGL_SWAP_LAYER_BUFFERS_ARB
#define WGL_SWAP_LAYER_BUFFERS_ARB 0x2006
#endif

#ifndef WGL_SWAP_METHOD_ARB
#define WGL_SWAP_METHOD_ARB 0x2007
#endif

#ifndef WGL_NUMBER_OVERLAYS_ARB
#define WGL_NUMBER_OVERLAYS_ARB 0x2008
#endif

#ifndef WGL_NUMBER_UNDERLAYS_ARB
#define WGL_NUMBER_UNDERLAYS_ARB 0x2009
#endif

#ifndef WGL_TRANSPARENT_ARB
#define WGL_TRANSPARENT_ARB 0x200A
#endif

#ifndef WGL_TRANSPARENT_RED_VALUE_ARB
#define WGL_TRANSPARENT_RED_VALUE_ARB 0x2037
#endif

#ifndef WGL_TRANSPARENT_GREEN_VALUE_ARB
#define WGL_TRANSPARENT_GREEN_VALUE_ARB 0x2038
#endif

#ifndef WGL_TRANSPARENT_BLUE_VALUE_ARB
#define WGL_TRANSPARENT_BLUE_VALUE_ARB 0x2039
#endif

#ifndef WGL_TRANSPARENT_ALPHA_VALUE_ARB
#define WGL_TRANSPARENT_ALPHA_VALUE_ARB 0x203A
#endif

#ifndef WGL_TRANSPARENT_INDEX_VALUE_ARB
#define WGL_TRANSPARENT_INDEX_VALUE_ARB 0x203B
#endif

#ifndef WGL_SHARE_DEPTH_ARB
#define WGL_SHARE_DEPTH_ARB 0x200C
#endif

#ifndef WGL_SHARE_STENCIL_ARB
#define WGL_SHARE_STENCIL_ARB 0x200D
#endif

#ifndef WGL_SHARE_ACCUM_ARB
#define WGL_SHARE_ACCUM_ARB 0x200E
#endif

#ifndef WGL_SUPPORT_GDI_ARB
#define WGL_SUPPORT_GDI_ARB 0x200F
#endif

#ifndef WGL_SUPPORT_OPENGL_ARB
#define WGL_SUPPORT_OPENGL_ARB 0x2010
#endif

#ifndef WGL_DOUBLE_BUFFER_ARB
#define WGL_DOUBLE_BUFFER_ARB 0x2011
#endif

#ifndef WGL_STEREO_ARB
#define WGL_STEREO_ARB 0x2012
#endif

#ifndef WGL_PIXEL_TYPE_ARB
#define WGL_PIXEL_TYPE_ARB 0x2013
#endif

#ifndef WGL_COLOR_BITS_ARB
#define WGL_COLOR_BITS_ARB 0x2014
#endif

#ifndef WGL_RED_BITS_ARB
#define WGL_RED_BITS_ARB 0x2015
#endif

#ifndef WGL_RED_SHIFT_ARB
#define WGL_RED_SHIFT_ARB 0x2016
#endif

#ifndef WGL_GREEN_BITS_ARB
#define WGL_GREEN_BITS_ARB 0x2017
#endif

#ifndef WGL_GREEN_SHIFT_ARB
#define WGL_GREEN_SHIFT_ARB 0x2018
#endif

#ifndef WGL_BLUE_BITS_ARB
#define WGL_BLUE_BITS_ARB 0x2019
#endif

#ifndef WGL_BLUE_SHIFT_ARB
#define WGL_BLUE_SHIFT_ARB 0x201A
#endif

#ifndef WGL_ALPHA_BITS_ARB
#define WGL_ALPHA_BITS_ARB 0x201B
#endif

#ifndef WGL_ALPHA_SHIFT_ARB
#define WGL_ALPHA_SHIFT_ARB 0x201C
#endif

#ifndef WGL_ACCUM_BITS_ARB
#define WGL_ACCUM_BITS_ARB 0x201D
#endif

#ifndef WGL_ACCUM_RED_BITS_ARB
#define WGL_ACCUM_RED_BITS_ARB 0x201E
#endif

#ifndef WGL_ACCUM_GREEN_BITS_ARB
#define WGL_ACCUM_GREEN_BITS_ARB 0x201F
#endif

#ifndef WGL_ACCUM_BLUE_BITS_ARB
#define WGL_ACCUM_BLUE_BITS_ARB 0x2020
#endif

#ifndef WGL_ACCUM_ALPHA_BITS_ARB
#define WGL_ACCUM_ALPHA_BITS_ARB 0x2021
#endif

#ifndef WGL_DEPTH_BITS_ARB
#define WGL_DEPTH_BITS_ARB 0x2022
#endif

#ifndef WGL_STENCIL_BITS_ARB
#define WGL_STENCIL_BITS_ARB 0x2023
#endif

#ifndef WGL_AUX_BUFFERS_ARB
#define WGL_AUX_BUFFERS_ARB 0x2024
#endif

#ifndef WGL_NO_ACCELERATION_ARB
#define WGL_NO_ACCELERATION_ARB 0x2025
#endif

#ifndef WGL_GENERIC_ACCELERATION_ARB
#define WGL_GENERIC_ACCELERATION_ARB 0x2026
#endif

#ifndef WGL_FULL_ACCELERATION_ARB
#define WGL_FULL_ACCELERATION_ARB 0x2027
#endif

#ifndef WGL_SWAP_EXCHANGE_ARB
#define WGL_SWAP_EXCHANGE_ARB 0x2028
#endif

#ifndef WGL_SWAP_COPY_ARB
#define WGL_SWAP_COPY_ARB 0x2029
#endif

#ifndef WGL_SWAP_UNDEFINED_ARB
#define WGL_SWAP_UNDEFINED_ARB 0x202A
#endif

#ifndef WGL_TYPE_RGBA_ARB
#define WGL_TYPE_RGBA_ARB 0x202B
#endif

#ifndef WGL_TYPE_COLORINDEX_ARB
#define WGL_TYPE_COLORINDEX_ARB 0x202C
#endif

#ifndef ERROR_INVALID_PIXEL_TYPE_ARB
#define ERROR_INVALID_PIXEL_TYPE_ARB 0x2043
#endif

#ifndef ERROR_INCOMPATIBLE_DEVICE_CONTEXTS_ARB
#define ERROR_INCOMPATIBLE_DEVICE_CONTEXTS_ARB 0x2054
#endif

#ifndef WGL_DRAW_TO_PBUFFER_ARB
#define WGL_DRAW_TO_PBUFFER_ARB 0x202D
#endif

#ifndef WGL_MAX_PBUFFER_PIXELS_ARB
#define WGL_MAX_PBUFFER_PIXELS_ARB 0x202E
#endif

#ifndef WGL_MAX_PBUFFER_WIDTH_ARB
#define WGL_MAX_PBUFFER_WIDTH_ARB 0x202F
#endif

#ifndef WGL_MAX_PBUFFER_HEIGHT_ARB
#define WGL_MAX_PBUFFER_HEIGHT_ARB 0x2030
#endif

#ifndef WGL_PBUFFER_LARGEST_ARB
#define WGL_PBUFFER_LARGEST_ARB 0x2033
#endif

#ifndef WGL_PBUFFER_WIDTH_ARB
#define WGL_PBUFFER_WIDTH_ARB 0x2034
#endif

#ifndef WGL_PBUFFER_HEIGHT_ARB
#define WGL_PBUFFER_HEIGHT_ARB 0x2035
#endif

#ifndef WGL_PBUFFER_LOST_ARB
#define WGL_PBUFFER_LOST_ARB 0x2036
#endif

#ifndef WGL_TRANSPARENT_RED_VALUE_ARB
#define WGL_TRANSPARENT_RED_VALUE_ARB 0x2037
#endif

#ifndef WGL_TRANSPARENT_GREEN_VALUE_ARB
#define WGL_TRANSPARENT_GREEN_VALUE_ARB 0x2038
#endif

#ifndef WGL_TRANSPARENT_BLUE_VALUE_ARB
#define WGL_TRANSPARENT_BLUE_VALUE_ARB 0x2039
#endif

#ifndef WGL_TRANSPARENT_ALPHA_VALUE_ARB
#define WGL_TRANSPARENT_ALPHA_VALUE_ARB 0x203A
#endif

#ifndef WGL_TRANSPARENT_INDEX_VALUE_ARB
#define WGL_TRANSPARENT_INDEX_VALUE_ARB 0x203B
#endif

#ifndef WGL_BIND_TO_TEXTURE_RGB_ARB
#define WGL_BIND_TO_TEXTURE_RGB_ARB 0x2070
#endif

#ifndef WGL_BIND_TO_TEXTURE_RGBA_ARB
#define WGL_BIND_TO_TEXTURE_RGBA_ARB 0x2071
#endif

#ifndef WGL_TEXTURE_FORMAT_ARB
#define WGL_TEXTURE_FORMAT_ARB 0x2072
#endif

#ifndef WGL_TEXTURE_TARGET_ARB
#define WGL_TEXTURE_TARGET_ARB 0x2073
#endif

#ifndef WGL_MIPMAP_TEXTURE_ARB
#define WGL_MIPMAP_TEXTURE_ARB 0x2074
#endif

#ifndef WGL_TEXTURE_RGB_ARB
#define WGL_TEXTURE_RGB_ARB 0x2075
#endif

#ifndef WGL_TEXTURE_RGBA_ARB
#define WGL_TEXTURE_RGBA_ARB 0x2076
#endif

#ifndef WGL_NO_TEXTURE_ARB
#define WGL_NO_TEXTURE_ARB 0x2077
#endif

#ifndef WGL_TEXTURE_CUBE_MAP_ARB
#define WGL_TEXTURE_CUBE_MAP_ARB 0x2078
#endif

#ifndef WGL_TEXTURE_1D_ARB
#define WGL_TEXTURE_1D_ARB 0x2079
#endif

#ifndef WGL_TEXTURE_2D_ARB
#define WGL_TEXTURE_2D_ARB 0x207A
#endif

#ifndef WGL_MIPMAP_LEVEL_ARB
#define WGL_MIPMAP_LEVEL_ARB 0x207B
#endif

#ifndef WGL_CUBE_MAP_FACE_ARB
#define WGL_CUBE_MAP_FACE_ARB 0x207C
#endif

#ifndef WGL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB
#define WGL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB 0x207D
#endif

#ifndef WGL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB
#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB 0x207E
#endif

#ifndef WGL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB
#define WGL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB 0x207F
#endif

#ifndef WGL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB
#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB 0x2080
#endif

#ifndef WGL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB
#define WGL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB 0x2081
#endif

#ifndef WGL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB
#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB 0x2082
#endif

#ifndef WGL_FRONT_LEFT_ARB
#define WGL_FRONT_LEFT_ARB 0x2083
#endif

#ifndef WGL_FRONT_RIGHT_ARB
#define WGL_FRONT_RIGHT_ARB 0x2084
#endif

#ifndef WGL_BACK_LEFT_ARB
#define WGL_BACK_LEFT_ARB 0x2085
#endif

#ifndef WGL_BACK_RIGHT_ARB
#define WGL_BACK_RIGHT_ARB 0x2086
#endif

#ifndef WGL_AUX0_ARB
#define WGL_AUX0_ARB 0x2087
#endif

#ifndef WGL_AUX1_ARB
#define WGL_AUX1_ARB 0x2088
#endif

#ifndef WGL_AUX2_ARB
#define WGL_AUX2_ARB 0x2089
#endif

#ifndef WGL_AUX3_ARB
#define WGL_AUX3_ARB 0x208A
#endif

#ifndef WGL_AUX4_ARB
#define WGL_AUX4_ARB 0x208B
#endif

#ifndef WGL_AUX5_ARB
#define WGL_AUX5_ARB 0x208C
#endif

#ifndef WGL_AUX6_ARB
#define WGL_AUX6_ARB 0x208D
#endif

#ifndef WGL_AUX7_ARB
#define WGL_AUX7_ARB 0x208E
#endif

#ifndef WGL_AUX8_ARB
#define WGL_AUX8_ARB 0x208F
#endif

#ifndef WGL_AUX9_ARB
#define WGL_AUX9_ARB 0x2090
#endif

#ifndef WGL_TYPE_RGBA_FLOAT_ARB
#define WGL_TYPE_RGBA_FLOAT_ARB 0x21A0
#endif

#ifndef WGL_FRAMEBUFFER_SRGB_CAPABLE_ARB
#define WGL_FRAMEBUFFER_SRGB_CAPABLE_ARB 0x20A9
#endif

#ifndef WGL_CONTEXT_DEBUG_BIT_ARB
#define WGL_CONTEXT_DEBUG_BIT_ARB 0x00000001
#endif

#ifndef WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB
#define WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB 0x00000002
#endif

#ifndef WGL_CONTEXT_MAJOR_VERSION_ARB
#define WGL_CONTEXT_MAJOR_VERSION_ARB 0x2091
#endif

#ifndef WGL_CONTEXT_MINOR_VERSION_ARB
#define WGL_CONTEXT_MINOR_VERSION_ARB 0x2092
#endif

#ifndef WGL_CONTEXT_LAYER_PLANE_ARB
#define WGL_CONTEXT_LAYER_PLANE_ARB 0x2093
#endif

#ifndef WGL_CONTEXT_FLAGS_ARB
#define WGL_CONTEXT_FLAGS_ARB 0x2094
#endif

#ifndef ERROR_INVALID_VERSION_ARB
#define ERROR_INVALID_VERSION_ARB 0x2095
#endif

#ifndef WGL_CONTEXT_PROFILE_MASK_ARB
#define WGL_CONTEXT_PROFILE_MASK_ARB 0x9126
#endif

#ifndef WGL_CONTEXT_CORE_PROFILE_BIT_ARB
#define WGL_CONTEXT_CORE_PROFILE_BIT_ARB 0x00000001
#endif

#ifndef WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB
#define WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB 0x00000002
#endif

#ifndef ERROR_INVALID_PROFILE_ARB
#define ERROR_INVALID_PROFILE_ARB 0x2096
#endif

#ifndef WGL_CONTEXT_ROBUST_ACCESS_BIT_ARB
#define WGL_CONTEXT_ROBUST_ACCESS_BIT_ARB 0x00000004
#endif

#ifndef WGL_LOSE_CONTEXT_ON_RESET_ARB
#define WGL_LOSE_CONTEXT_ON_RESET_ARB 0x8252
#endif

#ifndef WGL_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB
#define WGL_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB 0x8256
#endif

#ifndef WGL_NO_RESET_NOTIFICATION_ARB
#define WGL_NO_RESET_NOTIFICATION_ARB 0x8261
#endif

#ifndef ERROR_INVALID_PIXEL_TYPE_EXT
#define ERROR_INVALID_PIXEL_TYPE_EXT 0x2043
#endif

#ifndef WGL_NUMBER_PIXEL_FORMATS_EXT
#define WGL_NUMBER_PIXEL_FORMATS_EXT 0x2000
#endif

#ifndef WGL_DRAW_TO_WINDOW_EXT
#define WGL_DRAW_TO_WINDOW_EXT 0x2001
#endif

#ifndef WGL_DRAW_TO_BITMAP_EXT
#define WGL_DRAW_TO_BITMAP_EXT 0x2002
#endif

#ifndef WGL_ACCELERATION_EXT
#define WGL_ACCELERATION_EXT 0x2003
#endif

#ifndef WGL_NEED_PALETTE_EXT
#define WGL_NEED_PALETTE_EXT 0x2004
#endif

#ifndef WGL_NEED_SYSTEM_PALETTE_EXT
#define WGL_NEED_SYSTEM_PALETTE_EXT 0x2005
#endif

#ifndef WGL_SWAP_LAYER_BUFFERS_EXT
#define WGL_SWAP_LAYER_BUFFERS_EXT 0x2006
#endif

#ifndef WGL_SWAP_METHOD_EXT
#define WGL_SWAP_METHOD_EXT 0x2007
#endif

#ifndef WGL_NUMBER_OVERLAYS_EXT
#define WGL_NUMBER_OVERLAYS_EXT 0x2008
#endif

#ifndef WGL_NUMBER_UNDERLAYS_EXT
#define WGL_NUMBER_UNDERLAYS_EXT 0x2009
#endif

#ifndef WGL_TRANSPARENT_EXT
#define WGL_TRANSPARENT_EXT 0x200A
#endif

#ifndef WGL_TRANSPARENT_VALUE_EXT
#define WGL_TRANSPARENT_VALUE_EXT 0x200B
#endif

#ifndef WGL_SHARE_DEPTH_EXT
#define WGL_SHARE_DEPTH_EXT 0x200C
#endif

#ifndef WGL_SHARE_STENCIL_EXT
#define WGL_SHARE_STENCIL_EXT 0x200D
#endif

#ifndef WGL_SHARE_ACCUM_EXT
#define WGL_SHARE_ACCUM_EXT 0x200E
#endif

#ifndef WGL_SUPPORT_GDI_EXT
#define WGL_SUPPORT_GDI_EXT 0x200F
#endif

#ifndef WGL_SUPPORT_OPENGL_EXT
#define WGL_SUPPORT_OPENGL_EXT 0x2010
#endif

#ifndef WGL_DOUBLE_BUFFER_EXT
#define WGL_DOUBLE_BUFFER_EXT 0x2011
#endif

#ifndef WGL_STEREO_EXT
#define WGL_STEREO_EXT 0x2012
#endif

#ifndef WGL_PIXEL_TYPE_EXT
#define WGL_PIXEL_TYPE_EXT 0x2013
#endif

#ifndef WGL_COLOR_BITS_EXT
#define WGL_COLOR_BITS_EXT 0x2014
#endif

#ifndef WGL_RED_BITS_EXT
#define WGL_RED_BITS_EXT 0x2015
#endif

#ifndef WGL_RED_SHIFT_EXT
#define WGL_RED_SHIFT_EXT 0x2016
#endif

#ifndef WGL_GREEN_BITS_EXT
#define WGL_GREEN_BITS_EXT 0x2017
#endif

#ifndef WGL_GREEN_SHIFT_EXT
#define WGL_GREEN_SHIFT_EXT 0x2018
#endif

#ifndef WGL_BLUE_BITS_EXT
#define WGL_BLUE_BITS_EXT 0x2019
#endif

#ifndef WGL_BLUE_SHIFT_EXT
#define WGL_BLUE_SHIFT_EXT 0x201A
#endif

#ifndef WGL_ALPHA_BITS_EXT
#define WGL_ALPHA_BITS_EXT 0x201B
#endif

#ifndef WGL_ALPHA_SHIFT_EXT
#define WGL_ALPHA_SHIFT_EXT 0x201C
#endif

#ifndef WGL_ACCUM_BITS_EXT
#define WGL_ACCUM_BITS_EXT 0x201D
#endif

#ifndef WGL_ACCUM_RED_BITS_EXT
#define WGL_ACCUM_RED_BITS_EXT 0x201E
#endif

#ifndef WGL_ACCUM_GREEN_BITS_EXT
#define WGL_ACCUM_GREEN_BITS_EXT 0x201F
#endif

#ifndef WGL_ACCUM_BLUE_BITS_EXT
#define WGL_ACCUM_BLUE_BITS_EXT 0x2020
#endif

#ifndef WGL_ACCUM_ALPHA_BITS_EXT
#define WGL_ACCUM_ALPHA_BITS_EXT 0x2021
#endif

#ifndef WGL_DEPTH_BITS_EXT
#define WGL_DEPTH_BITS_EXT 0x2022
#endif

#ifndef WGL_STENCIL_BITS_EXT
#define WGL_STENCIL_BITS_EXT 0x2023
#endif

#ifndef WGL_AUX_BUFFERS_EXT
#define WGL_AUX_BUFFERS_EXT 0x2024
#endif

#ifndef WGL_NO_ACCELERATION_EXT
#define WGL_NO_ACCELERATION_EXT 0x2025
#endif

#ifndef WGL_GENERIC_ACCELERATION_EXT
#define WGL_GENERIC_ACCELERATION_EXT 0x2026
#endif

#ifndef WGL_FULL_ACCELERATION_EXT
#define WGL_FULL_ACCELERATION_EXT 0x2027
#endif

#ifndef WGL_SWAP_EXCHANGE_EXT
#define WGL_SWAP_EXCHANGE_EXT 0x2028
#endif

#ifndef WGL_SWAP_COPY_EXT
#define WGL_SWAP_COPY_EXT 0x2029
#endif

#ifndef WGL_SWAP_UNDEFINED_EXT
#define WGL_SWAP_UNDEFINED_EXT 0x202A
#endif

#ifndef WGL_TYPE_RGBA_EXT
#define WGL_TYPE_RGBA_EXT 0x202B
#endif

#ifndef WGL_TYPE_COLORINDEX_EXT
#define WGL_TYPE_COLORINDEX_EXT 0x202C
#endif

#ifndef WGL_DRAW_TO_PBUFFER_EXT
#define WGL_DRAW_TO_PBUFFER_EXT 0x202D
#endif

#ifndef WGL_MAX_PBUFFER_PIXELS_EXT
#define WGL_MAX_PBUFFER_PIXELS_EXT 0x202E
#endif

#ifndef WGL_MAX_PBUFFER_WIDTH_EXT
#define WGL_MAX_PBUFFER_WIDTH_EXT 0x202F
#endif

#ifndef WGL_MAX_PBUFFER_HEIGHT_EXT
#define WGL_MAX_PBUFFER_HEIGHT_EXT 0x2030
#endif

#ifndef WGL_OPTIMAL_PBUFFER_WIDTH_EXT
#define WGL_OPTIMAL_PBUFFER_WIDTH_EXT 0x2031
#endif

#ifndef WGL_OPTIMAL_PBUFFER_HEIGHT_EXT
#define WGL_OPTIMAL_PBUFFER_HEIGHT_EXT 0x2032
#endif

#ifndef WGL_PBUFFER_LARGEST_EXT
#define WGL_PBUFFER_LARGEST_EXT 0x2033
#endif

#ifndef WGL_PBUFFER_WIDTH_EXT
#define WGL_PBUFFER_WIDTH_EXT 0x2034
#endif

#ifndef WGL_PBUFFER_HEIGHT_EXT
#define WGL_PBUFFER_HEIGHT_EXT 0x2035
#endif

#ifndef WGL_DEPTH_FLOAT_EXT
#define WGL_DEPTH_FLOAT_EXT 0x2040
#endif

#ifndef WGL_SAMPLE_BUFFERS_3DFX
#define WGL_SAMPLE_BUFFERS_3DFX 0x2060
#endif

#ifndef WGL_SAMPLES_3DFX
#define WGL_SAMPLES_3DFX 0x2061
#endif

#ifndef WGL_SAMPLE_BUFFERS_EXT
#define WGL_SAMPLE_BUFFERS_EXT 0x2041
#endif

#ifndef WGL_SAMPLES_EXT
#define WGL_SAMPLES_EXT 0x2042
#endif

#ifndef WGL_DIGITAL_VIDEO_CURSOR_ALPHA_FRAMEBUFFER_I3D
#define WGL_DIGITAL_VIDEO_CURSOR_ALPHA_FRAMEBUFFER_I3D 0x2050
#endif

#ifndef WGL_DIGITAL_VIDEO_CURSOR_ALPHA_VALUE_I3D
#define WGL_DIGITAL_VIDEO_CURSOR_ALPHA_VALUE_I3D 0x2051
#endif

#ifndef WGL_DIGITAL_VIDEO_CURSOR_INCLUDED_I3D
#define WGL_DIGITAL_VIDEO_CURSOR_INCLUDED_I3D 0x2052
#endif

#ifndef WGL_DIGITAL_VIDEO_GAMMA_CORRECTED_I3D
#define WGL_DIGITAL_VIDEO_GAMMA_CORRECTED_I3D 0x2053
#endif

#ifndef WGL_GAMMA_TABLE_SIZE_I3D
#define WGL_GAMMA_TABLE_SIZE_I3D 0x204E
#endif

#ifndef WGL_GAMMA_EXCLUDE_DESKTOP_I3D
#define WGL_GAMMA_EXCLUDE_DESKTOP_I3D 0x204F
#endif

#ifndef WGL_GENLOCK_SOURCE_MULTIVIEW_I3D
#define WGL_GENLOCK_SOURCE_MULTIVIEW_I3D 0x2044
#endif

#ifndef WGL_GENLOCK_SOURCE_EXTENAL_SYNC_I3D
#define WGL_GENLOCK_SOURCE_EXTENAL_SYNC_I3D 0x2045
#endif

#ifndef WGL_GENLOCK_SOURCE_EXTENAL_FIELD_I3D
#define WGL_GENLOCK_SOURCE_EXTENAL_FIELD_I3D 0x2046
#endif

#ifndef WGL_GENLOCK_SOURCE_EXTENAL_TTL_I3D
#define WGL_GENLOCK_SOURCE_EXTENAL_TTL_I3D 0x2047
#endif

#ifndef WGL_GENLOCK_SOURCE_DIGITAL_SYNC_I3D
#define WGL_GENLOCK_SOURCE_DIGITAL_SYNC_I3D 0x2048
#endif

#ifndef WGL_GENLOCK_SOURCE_DIGITAL_FIELD_I3D
#define WGL_GENLOCK_SOURCE_DIGITAL_FIELD_I3D 0x2049
#endif

#ifndef WGL_GENLOCK_SOURCE_EDGE_FALLING_I3D
#define WGL_GENLOCK_SOURCE_EDGE_FALLING_I3D 0x204A
#endif

#ifndef WGL_GENLOCK_SOURCE_EDGE_RISING_I3D
#define WGL_GENLOCK_SOURCE_EDGE_RISING_I3D 0x204B
#endif

#ifndef WGL_GENLOCK_SOURCE_EDGE_BOTH_I3D
#define WGL_GENLOCK_SOURCE_EDGE_BOTH_I3D 0x204C
#endif

#ifndef WGL_IMAGE_BUFFER_MIN_ACCESS_I3D
#define WGL_IMAGE_BUFFER_MIN_ACCESS_I3D 0x00000001
#endif

#ifndef WGL_IMAGE_BUFFER_LOCK_I3D
#define WGL_IMAGE_BUFFER_LOCK_I3D 0x00000002
#endif

#ifndef WGL_BIND_TO_TEXTURE_DEPTH_NV
#define WGL_BIND_TO_TEXTURE_DEPTH_NV 0x20A3
#endif

#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_DEPTH_NV
#define WGL_BIND_TO_TEXTURE_RECTANGLE_DEPTH_NV 0x20A4
#endif

#ifndef WGL_DEPTH_TEXTURE_FORMAT_NV
#define WGL_DEPTH_TEXTURE_FORMAT_NV 0x20A5
#endif

#ifndef WGL_TEXTURE_DEPTH_COMPONENT_NV
#define WGL_TEXTURE_DEPTH_COMPONENT_NV 0x20A6
#endif

#ifndef WGL_DEPTH_COMPONENT_NV
#define WGL_DEPTH_COMPONENT_NV 0x20A7
#endif

#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_RGB_NV
#define WGL_BIND_TO_TEXTURE_RECTANGLE_RGB_NV 0x20A0
#endif

#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_RGBA_NV
#define WGL_BIND_TO_TEXTURE_RECTANGLE_RGBA_NV 0x20A1
#endif

#ifndef WGL_TEXTURE_RECTANGLE_NV
#define WGL_TEXTURE_RECTANGLE_NV 0x20A2
#endif

#ifndef WGL_TYPE_RGBA_FLOAT_ATI
#define WGL_TYPE_RGBA_FLOAT_ATI 0x21A0
#endif

#ifndef WGL_FLOAT_COMPONENTS_NV
#define WGL_FLOAT_COMPONENTS_NV 0x20B0
#endif

#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_R_NV
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_R_NV 0x20B1
#endif

#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RG_NV
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RG_NV 0x20B2
#endif

#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGB_NV
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGB_NV 0x20B3
#endif

#ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGBA_NV
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGBA_NV 0x20B4
#endif

#ifndef WGL_TEXTURE_FLOAT_R_NV
#define WGL_TEXTURE_FLOAT_R_NV 0x20B5
#endif

#ifndef WGL_TEXTURE_FLOAT_RG_NV
#define WGL_TEXTURE_FLOAT_RG_NV 0x20B6
#endif

#ifndef WGL_TEXTURE_FLOAT_RGB_NV
#define WGL_TEXTURE_FLOAT_RGB_NV 0x20B7
#endif

#ifndef WGL_TEXTURE_FLOAT_RGBA_NV
#define WGL_TEXTURE_FLOAT_RGBA_NV 0x20B8
#endif

#ifndef WGL_STEREO_EMITTER_ENABLE_3DL
#define WGL_STEREO_EMITTER_ENABLE_3DL 0x2055
#endif

#ifndef WGL_STEREO_EMITTER_DISABLE_3DL
#define WGL_STEREO_EMITTER_DISABLE_3DL 0x2056
#endif

#ifndef WGL_STEREO_POLARITY_NORMAL_3DL
#define WGL_STEREO_POLARITY_NORMAL_3DL 0x2057
#endif

#ifndef WGL_STEREO_POLARITY_INVERT_3DL
#define WGL_STEREO_POLARITY_INVERT_3DL 0x2058
#endif

#ifndef WGL_TYPE_RGBA_UNSIGNED_FLOAT_EXT
#define WGL_TYPE_RGBA_UNSIGNED_FLOAT_EXT 0x20A8
#endif

#ifndef WGL_FRAMEBUFFER_SRGB_CAPABLE_EXT
#define WGL_FRAMEBUFFER_SRGB_CAPABLE_EXT 0x20A9
#endif

#ifndef WGL_NUM_VIDEO_SLOTS_NV
#define WGL_NUM_VIDEO_SLOTS_NV 0x20F0
#endif

#ifndef WGL_BIND_TO_VIDEO_RGB_NV
#define WGL_BIND_TO_VIDEO_RGB_NV 0x20C0
#endif

#ifndef WGL_BIND_TO_VIDEO_RGBA_NV
#define WGL_BIND_TO_VIDEO_RGBA_NV 0x20C1
#endif

#ifndef WGL_BIND_TO_VIDEO_RGB_AND_DEPTH_NV
#define WGL_BIND_TO_VIDEO_RGB_AND_DEPTH_NV 0x20C2
#endif

#ifndef WGL_VIDEO_OUT_COLOR_NV
#define WGL_VIDEO_OUT_COLOR_NV 0x20C3
#endif

#ifndef WGL_VIDEO_OUT_ALPHA_NV
#define WGL_VIDEO_OUT_ALPHA_NV 0x20C4
#endif

#ifndef WGL_VIDEO_OUT_DEPTH_NV
#define WGL_VIDEO_OUT_DEPTH_NV 0x20C5
#endif

#ifndef WGL_VIDEO_OUT_COLOR_AND_ALPHA_NV
#define WGL_VIDEO_OUT_COLOR_AND_ALPHA_NV 0x20C6
#endif

#ifndef WGL_VIDEO_OUT_COLOR_AND_DEPTH_NV
#define WGL_VIDEO_OUT_COLOR_AND_DEPTH_NV 0x20C7
#endif

#ifndef WGL_VIDEO_OUT_FRAME
#define WGL_VIDEO_OUT_FRAME 0x20C8
#endif

#ifndef WGL_VIDEO_OUT_FIELD_1
#define WGL_VIDEO_OUT_FIELD_1 0x20C9
#endif

#ifndef WGL_VIDEO_OUT_FIELD_2
#define WGL_VIDEO_OUT_FIELD_2 0x20CA
#endif

#ifndef WGL_VIDEO_OUT_STACKED_FIELDS_1_2
#define WGL_VIDEO_OUT_STACKED_FIELDS_1_2 0x20CB
#endif

#ifndef WGL_VIDEO_OUT_STACKED_FIELDS_2_1
#define WGL_VIDEO_OUT_STACKED_FIELDS_2_1 0x20CC
#endif

#ifndef WGL_ERROR_INCOMPATIBLE_AFFINITY_MASKS_NV
#define WGL_ERROR_INCOMPATIBLE_AFFINITY_MASKS_NV 0x20D0
#endif

#ifndef WGL_ERROR_MISSING_AFFINITY_MASK_NV
#define WGL_ERROR_MISSING_AFFINITY_MASK_NV 0x20D1
#endif

#ifndef WGL_GPU_VENDOR_AMD
#define WGL_GPU_VENDOR_AMD 0x1F00
#endif

#ifndef WGL_GPU_RENDERER_STRING_AMD
#define WGL_GPU_RENDERER_STRING_AMD 0x1F01
#endif

#ifndef WGL_GPU_OPENGL_VERSION_STRING_AMD
#define WGL_GPU_OPENGL_VERSION_STRING_AMD 0x1F02
#endif

#ifndef WGL_GPU_FASTEST_TARGET_GPUS_AMD
#define WGL_GPU_FASTEST_TARGET_GPUS_AMD 0x21A2
#endif

#ifndef WGL_GPU_RAM_AMD
#define WGL_GPU_RAM_AMD 0x21A3
#endif

#ifndef WGL_GPU_CLOCK_AMD
#define WGL_GPU_CLOCK_AMD 0x21A4
#endif

#ifndef WGL_GPU_NUM_PIPES_AMD
#define WGL_GPU_NUM_PIPES_AMD 0x21A5
#endif

#ifndef WGL_GPU_NUM_SIMD_AMD
#define WGL_GPU_NUM_SIMD_AMD 0x21A6
#endif

#ifndef WGL_GPU_NUM_RB_AMD
#define WGL_GPU_NUM_RB_AMD 0x21A7
#endif

#ifndef WGL_GPU_NUM_SPI_AMD
#define WGL_GPU_NUM_SPI_AMD 0x21A8
#endif

#ifndef WGL_UNIQUE_ID_NV
#define WGL_UNIQUE_ID_NV 0x20CE
#endif

#ifndef WGL_NUM_VIDEO_CAPTURE_SLOTS_NV
#define WGL_NUM_VIDEO_CAPTURE_SLOTS_NV 0x20CF
#endif

#ifndef WGL_COVERAGE_SAMPLES_NV
#define WGL_COVERAGE_SAMPLES_NV 0x2042
#endif

#ifndef WGL_COLOR_SAMPLES_NV
#define WGL_COLOR_SAMPLES_NV 0x20B9
#endif

#ifndef WGL_CONTEXT_ES2_PROFILE_BIT_EXT
#define WGL_CONTEXT_ES2_PROFILE_BIT_EXT 0x00000004
#endif

#ifndef WGL_ACCESS_READ_ONLY_NV
#define WGL_ACCESS_READ_ONLY_NV 0x00000000
#endif

#ifndef WGL_ACCESS_READ_WRITE_NV
#define WGL_ACCESS_READ_WRITE_NV 0x00000001
#endif

#ifndef WGL_ACCESS_WRITE_DISCARD_NV
#define WGL_ACCESS_WRITE_DISCARD_NV 0x00000002
#endif

typedef HGLRC (APIENTRY *wglGetCurrentContextFunc)();
extern wglGetCurrentContextFunc _wglGetCurrentContext;
#define wglGetCurrentContext _wglGetCurrentContext
typedef BOOL (APIENTRY *wglCopyContextFunc)(HGLRC hglrcSrc, HGLRC hglrcDst, UINT mask);
extern wglCopyContextFunc _wglCopyContext;
#define wglCopyContext _wglCopyContext
typedef int (APIENTRY *wglChoosePixelFormatFunc)(HDC hDc, void* pPfd);
extern wglChoosePixelFormatFunc _wglChoosePixelFormat;
#define wglChoosePixelFormat _wglChoosePixelFormat
typedef int (APIENTRY *wglDescribePixelFormatFunc)(HDC hdc, int ipfd, UINT cjpfd, void* ppfd);
extern wglDescribePixelFormatFunc _wglDescribePixelFormat;
#define wglDescribePixelFormat _wglDescribePixelFormat
typedef HDC (APIENTRY *wglGetCurrentDCFunc)();
extern wglGetCurrentDCFunc _wglGetCurrentDC;
#define wglGetCurrentDC _wglGetCurrentDC
typedef PROC (APIENTRY *wglGetDefaultProcAddressFunc)(LPCSTR lpszProc);
extern wglGetDefaultProcAddressFunc _wglGetDefaultProcAddress;
#define wglGetDefaultProcAddress _wglGetDefaultProcAddress
typedef int (APIENTRY *wglGetPixelFormatFunc)(HDC hdc);
extern wglGetPixelFormatFunc _wglGetPixelFormat;
#define wglGetPixelFormat _wglGetPixelFormat
typedef BOOL (APIENTRY *wglSetPixelFormatFunc)(HDC hdc, int ipfd, void* ppfd);
extern wglSetPixelFormatFunc _wglSetPixelFormat;
#define wglSetPixelFormat _wglSetPixelFormat
typedef BOOL (APIENTRY *wglSwapBuffersFunc)(HDC hdc);
extern wglSwapBuffersFunc _wglSwapBuffers;
#define wglSwapBuffers _wglSwapBuffers
typedef BOOL (APIENTRY *wglShareListsFunc)(HGLRC hrcSrvShare, HGLRC hrcSrvSource);
extern wglShareListsFunc _wglShareLists;
#define wglShareLists _wglShareLists
typedef HGLRC (APIENTRY *wglCreateLayerContextFunc)(HDC hDc, int level);
extern wglCreateLayerContextFunc _wglCreateLayerContext;
#define wglCreateLayerContext _wglCreateLayerContext
typedef BOOL (APIENTRY *wglDescribeLayerPlaneFunc)(HDC hDc, int pixelFormat, int layerPlane, UINT nBytes, void* plpd);
extern wglDescribeLayerPlaneFunc _wglDescribeLayerPlane;
#define wglDescribeLayerPlane _wglDescribeLayerPlane
typedef int (APIENTRY *wglSetLayerPaletteEntriesFunc)(HDC hdc, int iLayerPlane, int iStart, int cEntries, void* pcr);
extern wglSetLayerPaletteEntriesFunc _wglSetLayerPaletteEntries;
#define wglSetLayerPaletteEntries _wglSetLayerPaletteEntries
typedef int (APIENTRY *wglGetLayerPaletteEntriesFunc)(HDC hdc, int iLayerPlane, int iStart, int cEntries, void* pcr);
extern wglGetLayerPaletteEntriesFunc _wglGetLayerPaletteEntries;
#define wglGetLayerPaletteEntries _wglGetLayerPaletteEntries
typedef BOOL (APIENTRY *wglRealizeLayerPaletteFunc)(HDC hdc, int iLayerPlane, BOOL bRealize);
extern wglRealizeLayerPaletteFunc _wglRealizeLayerPalette;
#define wglRealizeLayerPalette _wglRealizeLayerPalette
typedef BOOL (APIENTRY *wglSwapLayerBuffersFunc)(HDC hdc, UINT fuFlags);
extern wglSwapLayerBuffersFunc _wglSwapLayerBuffers;
#define wglSwapLayerBuffers _wglSwapLayerBuffers
typedef BOOL (APIENTRY *wglUseFontBitmapsAFunc)(HDC hDC, DWORD first, DWORD count, DWORD listBase);
extern wglUseFontBitmapsAFunc _wglUseFontBitmapsA;
#define wglUseFontBitmapsA _wglUseFontBitmapsA
typedef BOOL (APIENTRY *wglUseFontBitmapsWFunc)(HDC hDC, DWORD first, DWORD count, DWORD listBase);
extern wglUseFontBitmapsWFunc _wglUseFontBitmapsW;
#define wglUseFontBitmapsW _wglUseFontBitmapsW
#ifndef WGL_ARB_pbuffer
DECLARE_HANDLE(HPBUFFERARB);
#endif
#ifndef WGL_EXT_pbuffer
DECLARE_HANDLE(HPBUFFEREXT);
#endif
#ifndef WGL_NV_present_video
DECLARE_HANDLE(HVIDEOOUTPUTDEVICENV);
#endif
#ifndef WGL_NV_video_output
DECLARE_HANDLE(HPVIDEODEV);
#endif
#ifndef WGL_NV_gpu_affinity
DECLARE_HANDLE(HPGPUNV);
DECLARE_HANDLE(HGPUNV);

typedef struct _GPU_DEVICE {
DWORD  cb;
CHAR   DeviceName[32];
CHAR   DeviceString[128];
DWORD  Flags;
RECT   rcVirtualScreen;
} GPU_DEVICE, *PGPU_DEVICE;
#endif
#ifndef WGL_NV_video_capture
DECLARE_HANDLE(HVIDEOINPUTDEVICENV);
#endif

typedef HANDLE (APIENTRY *wglCreateBufferRegionARBFunc)(HDC hDC, int iLayerPlane, UINT uType);
extern wglCreateBufferRegionARBFunc _wglCreateBufferRegionARB;
#define wglCreateBufferRegionARB _wglCreateBufferRegionARB
typedef VOID (APIENTRY *wglDeleteBufferRegionARBFunc)(HANDLE hRegion);
extern wglDeleteBufferRegionARBFunc _wglDeleteBufferRegionARB;
#define wglDeleteBufferRegionARB _wglDeleteBufferRegionARB
typedef BOOL (APIENTRY *wglSaveBufferRegionARBFunc)(HANDLE hRegion, int x, int y, int width, int height);
extern wglSaveBufferRegionARBFunc _wglSaveBufferRegionARB;
#define wglSaveBufferRegionARB _wglSaveBufferRegionARB
typedef BOOL (APIENTRY *wglRestoreBufferRegionARBFunc)(HANDLE hRegion, int x, int y, int width, int height, int xSrc, int ySrc);
extern wglRestoreBufferRegionARBFunc _wglRestoreBufferRegionARB;
#define wglRestoreBufferRegionARB _wglRestoreBufferRegionARB
typedef const char * (APIENTRY *wglGetExtensionsStringARBFunc)(HDC hdc);
extern wglGetExtensionsStringARBFunc _wglGetExtensionsStringARB;
#define wglGetExtensionsStringARB _wglGetExtensionsStringARB
typedef BOOL (APIENTRY *wglGetPixelFormatAttribivARBFunc)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int* piAttributes, int* piValues);
extern wglGetPixelFormatAttribivARBFunc _wglGetPixelFormatAttribivARB;
#define wglGetPixelFormatAttribivARB _wglGetPixelFormatAttribivARB
typedef BOOL (APIENTRY *wglGetPixelFormatAttribfvARBFunc)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int* piAttributes, FLOAT* pfValues);
extern wglGetPixelFormatAttribfvARBFunc _wglGetPixelFormatAttribfvARB;
#define wglGetPixelFormatAttribfvARB _wglGetPixelFormatAttribfvARB
typedef BOOL (APIENTRY *wglChoosePixelFormatARBFunc)(HDC hdc, int* piAttribIList, FLOAT* pfAttribFList, UINT nMaxFormats, int* piFormats, UINT* nNumFormats);
extern wglChoosePixelFormatARBFunc _wglChoosePixelFormatARB;
#define wglChoosePixelFormatARB _wglChoosePixelFormatARB
typedef BOOL (APIENTRY *wglMakeContextCurrentARBFunc)(HDC hDrawDC, HDC hReadDC, HGLRC hglrc);
extern wglMakeContextCurrentARBFunc _wglMakeContextCurrentARB;
#define wglMakeContextCurrentARB _wglMakeContextCurrentARB
typedef HDC (APIENTRY *wglGetCurrentReadDCARBFunc)();
extern wglGetCurrentReadDCARBFunc _wglGetCurrentReadDCARB;
#define wglGetCurrentReadDCARB _wglGetCurrentReadDCARB
typedef HPBUFFERARB (APIENTRY *wglCreatePbufferARBFunc)(HDC hDC, int iPixelFormat, int iWidth, int iHeight, int* piAttribList);
extern wglCreatePbufferARBFunc _wglCreatePbufferARB;
#define wglCreatePbufferARB _wglCreatePbufferARB
typedef HDC (APIENTRY *wglGetPbufferDCARBFunc)(HPBUFFERARB hPbuffer);
extern wglGetPbufferDCARBFunc _wglGetPbufferDCARB;
#define wglGetPbufferDCARB _wglGetPbufferDCARB
typedef int (APIENTRY *wglReleasePbufferDCARBFunc)(HPBUFFERARB hPbuffer, HDC hDC);
extern wglReleasePbufferDCARBFunc _wglReleasePbufferDCARB;
#define wglReleasePbufferDCARB _wglReleasePbufferDCARB
typedef BOOL (APIENTRY *wglDestroyPbufferARBFunc)(HPBUFFERARB hPbuffer);
extern wglDestroyPbufferARBFunc _wglDestroyPbufferARB;
#define wglDestroyPbufferARB _wglDestroyPbufferARB
typedef BOOL (APIENTRY *wglQueryPbufferARBFunc)(HPBUFFERARB hPbuffer, int iAttribute, int* piValue);
extern wglQueryPbufferARBFunc _wglQueryPbufferARB;
#define wglQueryPbufferARB _wglQueryPbufferARB
typedef BOOL (APIENTRY *wglBindTexImageARBFunc)(HPBUFFERARB hPbuffer, int iBuffer);
extern wglBindTexImageARBFunc _wglBindTexImageARB;
#define wglBindTexImageARB _wglBindTexImageARB
typedef BOOL (APIENTRY *wglReleaseTexImageARBFunc)(HPBUFFERARB hPbuffer, int iBuffer);
extern wglReleaseTexImageARBFunc _wglReleaseTexImageARB;
#define wglReleaseTexImageARB _wglReleaseTexImageARB
typedef BOOL (APIENTRY *wglSetPbufferAttribARBFunc)(HPBUFFERARB hPbuffer, int* piAttribList);
extern wglSetPbufferAttribARBFunc _wglSetPbufferAttribARB;
#define wglSetPbufferAttribARB _wglSetPbufferAttribARB
typedef HGLRC (APIENTRY *wglCreateContextAttribsARBFunc)(HDC hDC, HGLRC hShareContext, int* attribList);
extern wglCreateContextAttribsARBFunc _wglCreateContextAttribsARB;
#define wglCreateContextAttribsARB _wglCreateContextAttribsARB
typedef GLboolean (APIENTRY *wglCreateDisplayColorTableEXTFunc)(GLushort id);
extern wglCreateDisplayColorTableEXTFunc _wglCreateDisplayColorTableEXT;
#define wglCreateDisplayColorTableEXT _wglCreateDisplayColorTableEXT
typedef GLboolean (APIENTRY *wglLoadDisplayColorTableEXTFunc)(GLushort* table, GLuint length);
extern wglLoadDisplayColorTableEXTFunc _wglLoadDisplayColorTableEXT;
#define wglLoadDisplayColorTableEXT _wglLoadDisplayColorTableEXT
typedef GLboolean (APIENTRY *wglBindDisplayColorTableEXTFunc)(GLushort id);
extern wglBindDisplayColorTableEXTFunc _wglBindDisplayColorTableEXT;
#define wglBindDisplayColorTableEXT _wglBindDisplayColorTableEXT
typedef VOID (APIENTRY *wglDestroyDisplayColorTableEXTFunc)(GLushort id);
extern wglDestroyDisplayColorTableEXTFunc _wglDestroyDisplayColorTableEXT;
#define wglDestroyDisplayColorTableEXT _wglDestroyDisplayColorTableEXT
typedef const char * (APIENTRY *wglGetExtensionsStringEXTFunc)();
extern wglGetExtensionsStringEXTFunc _wglGetExtensionsStringEXT;
#define wglGetExtensionsStringEXT _wglGetExtensionsStringEXT
typedef BOOL (APIENTRY *wglMakeContextCurrentEXTFunc)(HDC hDrawDC, HDC hReadDC, HGLRC hglrc);
extern wglMakeContextCurrentEXTFunc _wglMakeContextCurrentEXT;
#define wglMakeContextCurrentEXT _wglMakeContextCurrentEXT
typedef HDC (APIENTRY *wglGetCurrentReadDCEXTFunc)();
extern wglGetCurrentReadDCEXTFunc _wglGetCurrentReadDCEXT;
#define wglGetCurrentReadDCEXT _wglGetCurrentReadDCEXT
typedef HPBUFFEREXT (APIENTRY *wglCreatePbufferEXTFunc)(HDC hDC, int iPixelFormat, int iWidth, int iHeight, int* piAttribList);
extern wglCreatePbufferEXTFunc _wglCreatePbufferEXT;
#define wglCreatePbufferEXT _wglCreatePbufferEXT
typedef HDC (APIENTRY *wglGetPbufferDCEXTFunc)(HPBUFFEREXT hPbuffer);
extern wglGetPbufferDCEXTFunc _wglGetPbufferDCEXT;
#define wglGetPbufferDCEXT _wglGetPbufferDCEXT
typedef int (APIENTRY *wglReleasePbufferDCEXTFunc)(HPBUFFEREXT hPbuffer, HDC hDC);
extern wglReleasePbufferDCEXTFunc _wglReleasePbufferDCEXT;
#define wglReleasePbufferDCEXT _wglReleasePbufferDCEXT
typedef BOOL (APIENTRY *wglDestroyPbufferEXTFunc)(HPBUFFEREXT hPbuffer);
extern wglDestroyPbufferEXTFunc _wglDestroyPbufferEXT;
#define wglDestroyPbufferEXT _wglDestroyPbufferEXT
typedef BOOL (APIENTRY *wglQueryPbufferEXTFunc)(HPBUFFEREXT hPbuffer, int iAttribute, int* piValue);
extern wglQueryPbufferEXTFunc _wglQueryPbufferEXT;
#define wglQueryPbufferEXT _wglQueryPbufferEXT
typedef BOOL (APIENTRY *wglGetPixelFormatAttribivEXTFunc)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int* piAttributes, int* piValues);
extern wglGetPixelFormatAttribivEXTFunc _wglGetPixelFormatAttribivEXT;
#define wglGetPixelFormatAttribivEXT _wglGetPixelFormatAttribivEXT
typedef BOOL (APIENTRY *wglGetPixelFormatAttribfvEXTFunc)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int* piAttributes, FLOAT* pfValues);
extern wglGetPixelFormatAttribfvEXTFunc _wglGetPixelFormatAttribfvEXT;
#define wglGetPixelFormatAttribfvEXT _wglGetPixelFormatAttribfvEXT
typedef BOOL (APIENTRY *wglChoosePixelFormatEXTFunc)(HDC hdc, int* piAttribIList, FLOAT* pfAttribFList, UINT nMaxFormats, int* piFormats, UINT* nNumFormats);
extern wglChoosePixelFormatEXTFunc _wglChoosePixelFormatEXT;
#define wglChoosePixelFormatEXT _wglChoosePixelFormatEXT
typedef BOOL (APIENTRY *wglSwapIntervalEXTFunc)(int interval);
extern wglSwapIntervalEXTFunc _wglSwapIntervalEXT;
#define wglSwapIntervalEXT _wglSwapIntervalEXT
typedef int (APIENTRY *wglGetSwapIntervalEXTFunc)();
extern wglGetSwapIntervalEXTFunc _wglGetSwapIntervalEXT;
#define wglGetSwapIntervalEXT _wglGetSwapIntervalEXT
typedef void* (APIENTRY *wglAllocateMemoryNVFunc)(GLsizei size, GLfloat readfreq, GLfloat writefreq, GLfloat priority);
extern wglAllocateMemoryNVFunc _wglAllocateMemoryNV;
#define wglAllocateMemoryNV _wglAllocateMemoryNV
typedef void (APIENTRY *wglFreeMemoryNVFunc)(void* pointer);
extern wglFreeMemoryNVFunc _wglFreeMemoryNV;
#define wglFreeMemoryNV VE_ASSERT(_wglFreeMemoryNV);_wglFreeMemoryNV
typedef BOOL (APIENTRY *wglGetSyncValuesOMLFunc)(HDC hdc, INT64* ust, INT64* msc, INT64* sbc);
extern wglGetSyncValuesOMLFunc _wglGetSyncValuesOML;
#define wglGetSyncValuesOML _wglGetSyncValuesOML
typedef BOOL (APIENTRY *wglGetMscRateOMLFunc)(HDC hdc, INT32* numerator, INT32* denominator);
extern wglGetMscRateOMLFunc _wglGetMscRateOML;
#define wglGetMscRateOML _wglGetMscRateOML
typedef INT64 (APIENTRY *wglSwapBuffersMscOMLFunc)(HDC hdc, INT64 target_msc, INT64 divisor, INT64 remainder);
extern wglSwapBuffersMscOMLFunc _wglSwapBuffersMscOML;
#define wglSwapBuffersMscOML _wglSwapBuffersMscOML
typedef INT64 (APIENTRY *wglSwapLayerBuffersMscOMLFunc)(HDC hdc, int fuPlanes, INT64 target_msc, INT64 divisor, INT64 remainder);
extern wglSwapLayerBuffersMscOMLFunc _wglSwapLayerBuffersMscOML;
#define wglSwapLayerBuffersMscOML _wglSwapLayerBuffersMscOML
typedef BOOL (APIENTRY *wglWaitForMscOMLFunc)(HDC hdc, INT64 target_msc, INT64 divisor, INT64 remainder, INT64* ust, INT64* msc, INT64* sbc);
extern wglWaitForMscOMLFunc _wglWaitForMscOML;
#define wglWaitForMscOML _wglWaitForMscOML
typedef BOOL (APIENTRY *wglWaitForSbcOMLFunc)(HDC hdc, INT64 target_sbc, INT64* ust, INT64* msc, INT64* sbc);
extern wglWaitForSbcOMLFunc _wglWaitForSbcOML;
#define wglWaitForSbcOML _wglWaitForSbcOML
typedef BOOL (APIENTRY *wglGetDigitalVideoParametersI3DFunc)(HDC hDC, int iAttribute, int* piValue);
extern wglGetDigitalVideoParametersI3DFunc _wglGetDigitalVideoParametersI3D;
#define wglGetDigitalVideoParametersI3D _wglGetDigitalVideoParametersI3D
typedef BOOL (APIENTRY *wglSetDigitalVideoParametersI3DFunc)(HDC hDC, int iAttribute, int* piValue);
extern wglSetDigitalVideoParametersI3DFunc _wglSetDigitalVideoParametersI3D;
#define wglSetDigitalVideoParametersI3D _wglSetDigitalVideoParametersI3D
typedef BOOL (APIENTRY *wglGetGammaTableParametersI3DFunc)(HDC hDC, int iAttribute, int* piValue);
extern wglGetGammaTableParametersI3DFunc _wglGetGammaTableParametersI3D;
#define wglGetGammaTableParametersI3D _wglGetGammaTableParametersI3D
typedef BOOL (APIENTRY *wglSetGammaTableParametersI3DFunc)(HDC hDC, int iAttribute, int* piValue);
extern wglSetGammaTableParametersI3DFunc _wglSetGammaTableParametersI3D;
#define wglSetGammaTableParametersI3D _wglSetGammaTableParametersI3D
typedef BOOL (APIENTRY *wglGetGammaTableI3DFunc)(HDC hDC, int iEntries, USHORT* puRed, USHORT* puGreen, USHORT* puBlue);
extern wglGetGammaTableI3DFunc _wglGetGammaTableI3D;
#define wglGetGammaTableI3D _wglGetGammaTableI3D
typedef BOOL (APIENTRY *wglSetGammaTableI3DFunc)(HDC hDC, int iEntries, USHORT* puRed, USHORT* puGreen, USHORT* puBlue);
extern wglSetGammaTableI3DFunc _wglSetGammaTableI3D;
#define wglSetGammaTableI3D _wglSetGammaTableI3D
typedef BOOL (APIENTRY *wglEnableGenlockI3DFunc)(HDC hDC);
extern wglEnableGenlockI3DFunc _wglEnableGenlockI3D;
#define wglEnableGenlockI3D _wglEnableGenlockI3D
typedef BOOL (APIENTRY *wglDisableGenlockI3DFunc)(HDC hDC);
extern wglDisableGenlockI3DFunc _wglDisableGenlockI3D;
#define wglDisableGenlockI3D _wglDisableGenlockI3D
typedef BOOL (APIENTRY *wglIsEnabledGenlockI3DFunc)(HDC hDC, BOOL* pFlag);
extern wglIsEnabledGenlockI3DFunc _wglIsEnabledGenlockI3D;
#define wglIsEnabledGenlockI3D _wglIsEnabledGenlockI3D
typedef BOOL (APIENTRY *wglGenlockSourceI3DFunc)(HDC hDC, UINT uSource);
extern wglGenlockSourceI3DFunc _wglGenlockSourceI3D;
#define wglGenlockSourceI3D _wglGenlockSourceI3D
typedef BOOL (APIENTRY *wglGetGenlockSourceI3DFunc)(HDC hDC, UINT* uSource);
extern wglGetGenlockSourceI3DFunc _wglGetGenlockSourceI3D;
#define wglGetGenlockSourceI3D _wglGetGenlockSourceI3D
typedef BOOL (APIENTRY *wglGenlockSourceEdgeI3DFunc)(HDC hDC, UINT uEdge);
extern wglGenlockSourceEdgeI3DFunc _wglGenlockSourceEdgeI3D;
#define wglGenlockSourceEdgeI3D _wglGenlockSourceEdgeI3D
typedef BOOL (APIENTRY *wglGetGenlockSourceEdgeI3DFunc)(HDC hDC, UINT* uEdge);
extern wglGetGenlockSourceEdgeI3DFunc _wglGetGenlockSourceEdgeI3D;
#define wglGetGenlockSourceEdgeI3D _wglGetGenlockSourceEdgeI3D
typedef BOOL (APIENTRY *wglGenlockSampleRateI3DFunc)(HDC hDC, UINT uRate);
extern wglGenlockSampleRateI3DFunc _wglGenlockSampleRateI3D;
#define wglGenlockSampleRateI3D _wglGenlockSampleRateI3D
typedef BOOL (APIENTRY *wglGetGenlockSampleRateI3DFunc)(HDC hDC, UINT* uRate);
extern wglGetGenlockSampleRateI3DFunc _wglGetGenlockSampleRateI3D;
#define wglGetGenlockSampleRateI3D _wglGetGenlockSampleRateI3D
typedef BOOL (APIENTRY *wglGenlockSourceDelayI3DFunc)(HDC hDC, UINT uDelay);
extern wglGenlockSourceDelayI3DFunc _wglGenlockSourceDelayI3D;
#define wglGenlockSourceDelayI3D _wglGenlockSourceDelayI3D
typedef BOOL (APIENTRY *wglGetGenlockSourceDelayI3DFunc)(HDC hDC, UINT* uDelay);
extern wglGetGenlockSourceDelayI3DFunc _wglGetGenlockSourceDelayI3D;
#define wglGetGenlockSourceDelayI3D _wglGetGenlockSourceDelayI3D
typedef BOOL (APIENTRY *wglQueryGenlockMaxSourceDelayI3DFunc)(HDC hDC, UINT* uMaxLineDelay, UINT* uMaxPixelDelay);
extern wglQueryGenlockMaxSourceDelayI3DFunc _wglQueryGenlockMaxSourceDelayI3D;
#define wglQueryGenlockMaxSourceDelayI3D _wglQueryGenlockMaxSourceDelayI3D
typedef LPVOID (APIENTRY *wglCreateImageBufferI3DFunc)(HDC hDC, DWORD dwSize, UINT uFlags);
extern wglCreateImageBufferI3DFunc _wglCreateImageBufferI3D;
#define wglCreateImageBufferI3D _wglCreateImageBufferI3D
typedef BOOL (APIENTRY *wglDestroyImageBufferI3DFunc)(HDC hDC, LPVOID pAddress);
extern wglDestroyImageBufferI3DFunc _wglDestroyImageBufferI3D;
#define wglDestroyImageBufferI3D _wglDestroyImageBufferI3D
typedef BOOL (APIENTRY *wglAssociateImageBufferEventsI3DFunc)(HDC hDC, HANDLE* pEvent, LPVOID* pAddress, DWORD* pSize, UINT count);
extern wglAssociateImageBufferEventsI3DFunc _wglAssociateImageBufferEventsI3D;
#define wglAssociateImageBufferEventsI3D _wglAssociateImageBufferEventsI3D
typedef BOOL (APIENTRY *wglReleaseImageBufferEventsI3DFunc)(HDC hDC, LPVOID* pAddress, UINT count);
extern wglReleaseImageBufferEventsI3DFunc _wglReleaseImageBufferEventsI3D;
#define wglReleaseImageBufferEventsI3D _wglReleaseImageBufferEventsI3D
typedef BOOL (APIENTRY *wglEnableFrameLockI3DFunc)();
extern wglEnableFrameLockI3DFunc _wglEnableFrameLockI3D;
#define wglEnableFrameLockI3D _wglEnableFrameLockI3D
typedef BOOL (APIENTRY *wglDisableFrameLockI3DFunc)();
extern wglDisableFrameLockI3DFunc _wglDisableFrameLockI3D;
#define wglDisableFrameLockI3D _wglDisableFrameLockI3D
typedef BOOL (APIENTRY *wglIsEnabledFrameLockI3DFunc)(BOOL* pFlag);
extern wglIsEnabledFrameLockI3DFunc _wglIsEnabledFrameLockI3D;
#define wglIsEnabledFrameLockI3D _wglIsEnabledFrameLockI3D
typedef BOOL (APIENTRY *wglQueryFrameLockMasterI3DFunc)(BOOL* pFlag);
extern wglQueryFrameLockMasterI3DFunc _wglQueryFrameLockMasterI3D;
#define wglQueryFrameLockMasterI3D _wglQueryFrameLockMasterI3D
typedef BOOL (APIENTRY *wglGetFrameUsageI3DFunc)(float* pUsage);
extern wglGetFrameUsageI3DFunc _wglGetFrameUsageI3D;
#define wglGetFrameUsageI3D _wglGetFrameUsageI3D
typedef BOOL (APIENTRY *wglBeginFrameTrackingI3DFunc)();
extern wglBeginFrameTrackingI3DFunc _wglBeginFrameTrackingI3D;
#define wglBeginFrameTrackingI3D _wglBeginFrameTrackingI3D
typedef BOOL (APIENTRY *wglEndFrameTrackingI3DFunc)();
extern wglEndFrameTrackingI3DFunc _wglEndFrameTrackingI3D;
#define wglEndFrameTrackingI3D _wglEndFrameTrackingI3D
typedef BOOL (APIENTRY *wglQueryFrameTrackingI3DFunc)(DWORD* pFrameCount, DWORD* pMissedFrames, float* pLastMissedUsage);
extern wglQueryFrameTrackingI3DFunc _wglQueryFrameTrackingI3D;
#define wglQueryFrameTrackingI3D _wglQueryFrameTrackingI3D
typedef BOOL (APIENTRY *wglSetStereoEmitterState3DLFunc)(HDC hDC, UINT uState);
extern wglSetStereoEmitterState3DLFunc _wglSetStereoEmitterState3DL;
#define wglSetStereoEmitterState3DL _wglSetStereoEmitterState3DL
typedef int (APIENTRY *wglEnumerateVideoDevicesNVFunc)(HDC hDC, HVIDEOOUTPUTDEVICENV* phDeviceList);
extern wglEnumerateVideoDevicesNVFunc _wglEnumerateVideoDevicesNV;
#define wglEnumerateVideoDevicesNV _wglEnumerateVideoDevicesNV
typedef BOOL (APIENTRY *wglBindVideoDeviceNVFunc)(HDC hDC, unsigned int uVideoSlot, HVIDEOOUTPUTDEVICENV hVideoDevice, int* piAttribList);
extern wglBindVideoDeviceNVFunc _wglBindVideoDeviceNV;
#define wglBindVideoDeviceNV _wglBindVideoDeviceNV
typedef BOOL (APIENTRY *wglQueryCurrentContextNVFunc)(int iAttribute, int* piValue);
extern wglQueryCurrentContextNVFunc _wglQueryCurrentContextNV;
#define wglQueryCurrentContextNV _wglQueryCurrentContextNV
typedef BOOL (APIENTRY *wglGetVideoDeviceNVFunc)(HDC hDC, int numDevices, HPVIDEODEV* hVideoDevice);
extern wglGetVideoDeviceNVFunc _wglGetVideoDeviceNV;
#define wglGetVideoDeviceNV _wglGetVideoDeviceNV
typedef BOOL (APIENTRY *wglReleaseVideoDeviceNVFunc)(HPVIDEODEV hVideoDevice);
extern wglReleaseVideoDeviceNVFunc _wglReleaseVideoDeviceNV;
#define wglReleaseVideoDeviceNV _wglReleaseVideoDeviceNV
typedef BOOL (APIENTRY *wglBindVideoImageNVFunc)(HPVIDEODEV hVideoDevice, HPBUFFERARB hPbuffer, int iVideoBuffer);
extern wglBindVideoImageNVFunc _wglBindVideoImageNV;
#define wglBindVideoImageNV _wglBindVideoImageNV
typedef BOOL (APIENTRY *wglReleaseVideoImageNVFunc)(HPBUFFERARB hPbuffer, int iVideoBuffer);
extern wglReleaseVideoImageNVFunc _wglReleaseVideoImageNV;
#define wglReleaseVideoImageNV _wglReleaseVideoImageNV
typedef BOOL (APIENTRY *wglSendPbufferToVideoNVFunc)(HPBUFFERARB hPbuffer, int iBufferType, unsigned long* pulCounterPbuffer, BOOL bBlock);
extern wglSendPbufferToVideoNVFunc _wglSendPbufferToVideoNV;
#define wglSendPbufferToVideoNV _wglSendPbufferToVideoNV
typedef BOOL (APIENTRY *wglGetVideoInfoNVFunc)(HPVIDEODEV hpVideoDevice, unsigned long* pulCounterOutputPbuffer, unsigned long* pulCounterOutputVideo);
extern wglGetVideoInfoNVFunc _wglGetVideoInfoNV;
#define wglGetVideoInfoNV _wglGetVideoInfoNV
typedef BOOL (APIENTRY *wglJoinSwapGroupNVFunc)(HDC hDC, GLuint group);
extern wglJoinSwapGroupNVFunc _wglJoinSwapGroupNV;
#define wglJoinSwapGroupNV _wglJoinSwapGroupNV
typedef BOOL (APIENTRY *wglBindSwapBarrierNVFunc)(GLuint group, GLuint barrier);
extern wglBindSwapBarrierNVFunc _wglBindSwapBarrierNV;
#define wglBindSwapBarrierNV _wglBindSwapBarrierNV
typedef BOOL (APIENTRY *wglQuerySwapGroupNVFunc)(HDC hDC, GLuint* group, GLuint* barrier);
extern wglQuerySwapGroupNVFunc _wglQuerySwapGroupNV;
#define wglQuerySwapGroupNV _wglQuerySwapGroupNV
typedef BOOL (APIENTRY *wglQueryMaxSwapGroupsNVFunc)(HDC hDC, GLuint* maxGroups, GLuint* maxBarriers);
extern wglQueryMaxSwapGroupsNVFunc _wglQueryMaxSwapGroupsNV;
#define wglQueryMaxSwapGroupsNV _wglQueryMaxSwapGroupsNV
typedef BOOL (APIENTRY *wglQueryFrameCountNVFunc)(HDC hDC, GLuint* count);
extern wglQueryFrameCountNVFunc _wglQueryFrameCountNV;
#define wglQueryFrameCountNV _wglQueryFrameCountNV
typedef BOOL (APIENTRY *wglResetFrameCountNVFunc)(HDC hDC);
extern wglResetFrameCountNVFunc _wglResetFrameCountNV;
#define wglResetFrameCountNV _wglResetFrameCountNV
typedef BOOL (APIENTRY *wglEnumGpusNVFunc)(UINT iGpuIndex, HGPUNV* phGpu);
extern wglEnumGpusNVFunc _wglEnumGpusNV;
#define wglEnumGpusNV _wglEnumGpusNV
typedef BOOL (APIENTRY *wglEnumGpuDevicesNVFunc)(HGPUNV hGpu, UINT iDeviceIndex, PGPU_DEVICE lpGpuDevice);
extern wglEnumGpuDevicesNVFunc _wglEnumGpuDevicesNV;
#define wglEnumGpuDevicesNV _wglEnumGpuDevicesNV
typedef HDC (APIENTRY *wglCreateAffinityDCNVFunc)(HGPUNV* phGpuList);
extern wglCreateAffinityDCNVFunc _wglCreateAffinityDCNV;
#define wglCreateAffinityDCNV _wglCreateAffinityDCNV
typedef BOOL (APIENTRY *wglEnumGpusFromAffinityDCNVFunc)(HDC hAffinityDC, UINT iGpuIndex, HGPUNV* hGpu);
extern wglEnumGpusFromAffinityDCNVFunc _wglEnumGpusFromAffinityDCNV;
#define wglEnumGpusFromAffinityDCNV _wglEnumGpusFromAffinityDCNV
typedef BOOL (APIENTRY *wglDeleteDCNVFunc)(HDC hdc);
extern wglDeleteDCNVFunc _wglDeleteDCNV;
#define wglDeleteDCNV _wglDeleteDCNV
typedef UINT (APIENTRY *wglGetGPUIDsAMDFunc)(UINT maxCount, UINT* ids);
extern wglGetGPUIDsAMDFunc _wglGetGPUIDsAMD;
#define wglGetGPUIDsAMD _wglGetGPUIDsAMD
typedef INT (APIENTRY *wglGetGPUInfoAMDFunc)(UINT id, int property, GLenum dataType, UINT size, void* data);
extern wglGetGPUInfoAMDFunc _wglGetGPUInfoAMD;
#define wglGetGPUInfoAMD _wglGetGPUInfoAMD
typedef UINT (APIENTRY *wglGetContextGPUIDAMDFunc)(HGLRC hglrc);
extern wglGetContextGPUIDAMDFunc _wglGetContextGPUIDAMD;
#define wglGetContextGPUIDAMD _wglGetContextGPUIDAMD
typedef HGLRC (APIENTRY *wglCreateAssociatedContextAMDFunc)(UINT id);
extern wglCreateAssociatedContextAMDFunc _wglCreateAssociatedContextAMD;
#define wglCreateAssociatedContextAMD _wglCreateAssociatedContextAMD
typedef HGLRC (APIENTRY *wglCreateAssociatedContextAttribsAMDFunc)(UINT id, HGLRC hShareContext, int* attribList);
extern wglCreateAssociatedContextAttribsAMDFunc _wglCreateAssociatedContextAttribsAMD;
#define wglCreateAssociatedContextAttribsAMD _wglCreateAssociatedContextAttribsAMD
typedef BOOL (APIENTRY *wglDeleteAssociatedContextAMDFunc)(HGLRC hglrc);
extern wglDeleteAssociatedContextAMDFunc _wglDeleteAssociatedContextAMD;
#define wglDeleteAssociatedContextAMD _wglDeleteAssociatedContextAMD
typedef BOOL (APIENTRY *wglMakeAssociatedContextCurrentAMDFunc)(HGLRC hglrc);
extern wglMakeAssociatedContextCurrentAMDFunc _wglMakeAssociatedContextCurrentAMD;
#define wglMakeAssociatedContextCurrentAMD _wglMakeAssociatedContextCurrentAMD
typedef HGLRC (APIENTRY *wglGetCurrentAssociatedContextAMDFunc)();
extern wglGetCurrentAssociatedContextAMDFunc _wglGetCurrentAssociatedContextAMD;
#define wglGetCurrentAssociatedContextAMD _wglGetCurrentAssociatedContextAMD
typedef VOID (APIENTRY *wglBlitContextFramebufferAMDFunc)(HGLRC dstCtx, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
extern wglBlitContextFramebufferAMDFunc _wglBlitContextFramebufferAMD;
#define wglBlitContextFramebufferAMD _wglBlitContextFramebufferAMD
typedef BOOL (APIENTRY *wglBindVideoCaptureDeviceNVFunc)(UINT uVideoSlot, HVIDEOINPUTDEVICENV hDevice);
extern wglBindVideoCaptureDeviceNVFunc _wglBindVideoCaptureDeviceNV;
#define wglBindVideoCaptureDeviceNV _wglBindVideoCaptureDeviceNV
typedef UINT (APIENTRY *wglEnumerateVideoCaptureDevicesNVFunc)(HDC hDc, HVIDEOINPUTDEVICENV* phDeviceList);
extern wglEnumerateVideoCaptureDevicesNVFunc _wglEnumerateVideoCaptureDevicesNV;
#define wglEnumerateVideoCaptureDevicesNV _wglEnumerateVideoCaptureDevicesNV
typedef BOOL (APIENTRY *wglLockVideoCaptureDeviceNVFunc)(HDC hDc, HVIDEOINPUTDEVICENV hDevice);
extern wglLockVideoCaptureDeviceNVFunc _wglLockVideoCaptureDeviceNV;
#define wglLockVideoCaptureDeviceNV _wglLockVideoCaptureDeviceNV
typedef BOOL (APIENTRY *wglQueryVideoCaptureDeviceNVFunc)(HDC hDc, HVIDEOINPUTDEVICENV hDevice, int iAttribute, int* piValue);
extern wglQueryVideoCaptureDeviceNVFunc _wglQueryVideoCaptureDeviceNV;
#define wglQueryVideoCaptureDeviceNV _wglQueryVideoCaptureDeviceNV
typedef BOOL (APIENTRY *wglReleaseVideoCaptureDeviceNVFunc)(HDC hDc, HVIDEOINPUTDEVICENV hDevice);
extern wglReleaseVideoCaptureDeviceNVFunc _wglReleaseVideoCaptureDeviceNV;
#define wglReleaseVideoCaptureDeviceNV _wglReleaseVideoCaptureDeviceNV
typedef BOOL (APIENTRY *wglCopyImageSubDataNVFunc)(HGLRC hSrcRC, GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, HGLRC hDstRC, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei width, GLsizei height, GLsizei depth);
extern wglCopyImageSubDataNVFunc _wglCopyImageSubDataNV;
#define wglCopyImageSubDataNV _wglCopyImageSubDataNV
typedef BOOL (APIENTRY *wglDXSetResourceShareHandleNVFunc)(void* dxObject, HANDLE shareHandle);
extern wglDXSetResourceShareHandleNVFunc _wglDXSetResourceShareHandleNV;
#define wglDXSetResourceShareHandleNV _wglDXSetResourceShareHandleNV
typedef HANDLE (APIENTRY *wglDXOpenDeviceNVFunc)(void* dxDevice);
extern wglDXOpenDeviceNVFunc _wglDXOpenDeviceNV;
#define wglDXOpenDeviceNV _wglDXOpenDeviceNV
typedef BOOL (APIENTRY *wglDXCloseDeviceNVFunc)(HANDLE hDevice);
extern wglDXCloseDeviceNVFunc _wglDXCloseDeviceNV;
#define wglDXCloseDeviceNV _wglDXCloseDeviceNV
typedef HANDLE (APIENTRY *wglDXRegisterObjectNVFunc)(HANDLE hDevice, void* dxObject, GLuint name, GLenum type, GLenum access);
extern wglDXRegisterObjectNVFunc _wglDXRegisterObjectNV;
#define wglDXRegisterObjectNV _wglDXRegisterObjectNV
typedef BOOL (APIENTRY *wglDXUnregisterObjectNVFunc)(HANDLE hDevice, HANDLE hObject);
extern wglDXUnregisterObjectNVFunc _wglDXUnregisterObjectNV;
#define wglDXUnregisterObjectNV _wglDXUnregisterObjectNV
typedef BOOL (APIENTRY *wglDXObjectAccessNVFunc)(HANDLE hObject, GLenum access);
extern wglDXObjectAccessNVFunc _wglDXObjectAccessNV;
#define wglDXObjectAccessNV _wglDXObjectAccessNV
typedef BOOL (APIENTRY *wglDXLockObjectsNVFunc)(HANDLE hDevice, GLint count, HANDLE* hObjects);
extern wglDXLockObjectsNVFunc _wglDXLockObjectsNV;
#define wglDXLockObjectsNV _wglDXLockObjectsNV
typedef BOOL (APIENTRY *wglDXUnlockObjectsNVFunc)(HANDLE hDevice, GLint count, HANDLE* hObjects);
extern wglDXUnlockObjectsNVFunc _wglDXUnlockObjectsNV;
#define wglDXUnlockObjectsNV _wglDXUnlockObjectsNV

void wglFuncload();

void wglFuncUnload();

}

#endif
